#!/usr/bin/env bash
# WireProxy Socks5 和 WARP Client 全局代理管理脚本
# Generated by github.com/halibotee

VERSION='1.0.1'

# 环境变量设置
export DEBIAN_FRONTEND=noninteractive

# 颜色函数
warning() { echo -e "\033[31m\033[01m$*\033[0m"; }  # 红色
error() { echo -e "\033[31m\033[01m$*\033[0m" && exit 1; }  # 红色
info() { echo -e "\033[32m\033[01m$*\033[0m"; }   # 绿色
hint() { echo -e "\033[33m\033[01m$*\033[0m"; }   # 黄色
reading() { read -rp "$(info "$1")" "$2"; }

# 清理函数
cleanup_resources() {
  rm -f /tmp/{ip,wireguard-go-*,best_mtu,statistics} 2>/dev/null
  exit 0
}

trap cleanup_resources EXIT INT TERM

# 检查root权限
check_root() {
  [ "$(id -u)" != 0 ] && error " 必须以root方式运行脚本，可以输入 sudo -i 后重新运行"
}

# 检测操作系统
check_operating_system() {
  if [ -s /etc/os-release ]; then
    SYS="$(grep -i pretty_name /etc/os-release | cut -d \" -f2)"
  elif [ -x "$(type -p hostnamectl)" ]; then
    SYS="$(hostnamectl | grep -i system | cut -d : -f2)"
  elif [ -x "$(type -p lsb_release)" ]; then
    SYS="$(lsb_release -sd)"
  elif [ -s /etc/lsb-release ]; then
    SYS="$(grep -i description /etc/lsb-release | cut -d \" -f2)"
  elif [ -s /etc/redhat-release ]; then
    SYS="$(grep . /etc/redhat-release)"
  elif [ -s /etc/issue ]; then
    SYS="$(grep . /etc/issue | cut -d '\' -f1 | sed '/^[ ]*$/d')"
  fi

  REGEX=("debian" "ubuntu" "centos|red hat|kernel|alma|rocky" "alpine" "arch linux|endeavouros" "fedora")
  RELEASE=("Debian" "Ubuntu" "CentOS" "Alpine" "Arch" "Fedora")

  for int in "${!REGEX[@]}"; do
    [[ "${SYS,,}" =~ ${REGEX[int]} ]] && SYSTEM="${RELEASE[int]}" && break
  done

  # 针对各厂运的订制系统
  if [ -z "$SYSTEM" ]; then
    [ -x "$(type -p yum)" ] && int=2 && SYSTEM='CentOS' || error " 不支持的操作系统: $SYS"
  fi
}

# 判断虚拟化
check_virt() {
  if [ "$1" = 'Alpine' ]; then
    VIRT=$(virt-what 2>/dev/null | tr '\n' ' ')
  else
    [ "$(type -p systemd-detect-virt)" ] && VIRT=$(systemd-detect-virt 2>/dev/null)
    [[ -z "$VIRT" && -x "$(type -p hostnamectl)" ]] && VIRT=$(hostnamectl | awk '/Virtualization:/{print $NF}')
  fi
  VIRT=${VIRT:-"unknown"}
}

# 获取IP信息
ip_info() {
  local CHECK_46="$1"
  if [[ "$2" =~ ^[0-9]+$ ]]; then
    local INTERFACE_SOCK5="--proxy socks5h://127.0.0.1:$2"
  elif [[ "$2" =~ ^[[:alnum:]]+$ ]]; then
    local INTERFACE_SOCK5="--interface $2"
  fi

  [ "$CHECK_46" = '6' ] && CHOOSE_IP_API='https://api-ipv6.ip.sb/geoip' || CHOOSE_IP_API='https://ipinfo.io/ip'
  IP_TRACE=$(curl --retry 2 -ksm5 $INTERFACE_SOCK5 https://www.cloudflare.com/cdn-cgi/trace 2>/dev/null | awk -F '=' '/^warp=/{print $NF}')
  if [ -n "$IP_TRACE" ]; then
    local API_IP=$(curl --retry 2 -ksm5 $INTERFACE_SOCK5 --user-agent Mozilla $CHOOSE_IP_API 2>/dev/null | sed 's/.*"ip":"\([^"]\+\)".*/\1/')
    [[ -n "$API_IP" && ! "$API_IP" =~ error[[:space:]]+code:[[:space:]]+1015 ]] && local IP_JSON=$(curl --retry 2 -ksm5 https://ip.forvps.gq/${API_IP} 2>/dev/null) || unset IP_JSON
    IP_JSON=${IP_JSON:-"$(curl --retry 3 -ks${CHECK_46}m5 $INTERFACE_SOCK5 --user-agent Mozilla https://ifconfig.co/json 2>/dev/null)"}

    if [ -n "$IP_JSON" ]; then
      local WAN=$(sed -En 's/.*"(ip|query)":[ ]*"([^"]+)".*/\2/p' <<< "$IP_JSON")
      local COUNTRY=$(sed -En 's/.*"country":[ ]*"([^"]+)".*/\1/p' <<< "$IP_JSON")
      local ASNORG=$(sed -En 's/.*"(isp|asn_org)":[ ]*"([^"]+)".*/\2/p' <<< "$IP_JSON")
    fi
  fi

  echo -e "trace=$IP_TRACE@\nip=$WAN@\ncountry=$COUNTRY@\nasnorg=$ASNORG\n"
}

# 获取IP信息 - WireProxy
get_wireproxy_ip() {
  unset WIREPROXY_SOCKS5 WIREPROXY_PORT WIREPROXY_WAN4 WIREPROXY_COUNTRY4 WIREPROXY_ASNORG4
  WIREPROXY_SOCKS5=$(ss -nltp 2>/dev/null | awk '/"wireproxy"/{print $4}')
  if [ -n "$WIREPROXY_SOCKS5" ]; then
    WIREPROXY_PORT=$(cut -d: -f2 <<< "$WIREPROXY_SOCKS5")
    local IP_RESULT4=$(ip_info 4 "$WIREPROXY_PORT")
    WIREPROXY_TRACE4=$(expr "$IP_RESULT4" : '.*trace=\([^@]*\).*')
    WIREPROXY_WAN4=$(expr "$IP_RESULT4" : '.*ip=\([^@]*\).*')
    WIREPROXY_COUNTRY4=$(expr "$IP_RESULT4" : '.*country=\([^@]*\).*')
    WIREPROXY_ASNORG4=$(expr "$IP_RESULT4" : '.*asnorg=\([^@]*\).*')
    
    local IP_RESULT6=$(ip_info 6 "$WIREPROXY_PORT")
    WIREPROXY_TRACE6=$(expr "$IP_RESULT6" : '.*trace=\([^@]*\).*')
    WIREPROXY_WAN6=$(expr "$IP_RESULT6" : '.*ip=\([^@]*\).*')
    WIREPROXY_COUNTRY6=$(expr "$IP_RESULT6" : '.*country=\([^@]*\).*')
    WIREPROXY_ASNORG6=$(expr "$IP_RESULT6" : '.*asnorg=\([^@]*\).*')
  fi
}

# 获取IP信息 - Client
get_client_ip() {
  unset CLIENT_SOCKS5 CLIENT_PORT CLIENT_WAN4 CLIENT_COUNTRY4 CLIENT_ASNORG4
  CLIENT_SOCKS5=$(ss -nltp 2>/dev/null | awk '/"warp-svc"/{print $4}')
  if [ -n "$CLIENT_SOCKS5" ]; then
    CLIENT_PORT=$(cut -d: -f2 <<< "$CLIENT_SOCKS5")
    local IP_RESULT4=$(ip_info 4 "$CLIENT_PORT")
    CLIENT_TRACE4=$(expr "$IP_RESULT4" : '.*trace=\([^@]*\).*')
    CLIENT_WAN4=$(expr "$IP_RESULT4" : '.*ip=\([^@]*\).*')
    CLIENT_COUNTRY4=$(expr "$IP_RESULT4" : '.*country=\([^@]*\).*')
    CLIENT_ASNORG4=$(expr "$IP_RESULT4" : '.*asnorg=\([^@]*\).*')
    
    local IP_RESULT6=$(ip_info 6 "$CLIENT_PORT")
    CLIENT_TRACE6=$(expr "$IP_RESULT6" : '.*trace=\([^@]*\).*')
    CLIENT_WAN6=$(expr "$IP_RESULT6" : '.*ip=\([^@]*\).*')
    CLIENT_COUNTRY6=$(expr "$IP_RESULT6" : '.*country=\([^@]*\).*')
    CLIENT_ASNORG6=$(expr "$IP_RESULT6" : '.*asnorg=\([^@]*\).*')
  fi
}

# 获取本机IP信息
get_native_ip() {
  unset WAN4 COUNTRY4 ASNORG4 WAN6 COUNTRY6 ASNORG6
  
  local IP_RESULT4=$(curl --retry 2 -4 -ksm5 --user-agent Mozilla https://ifconfig.co/json 2>/dev/null)
  if [ -n "$IP_RESULT4" ]; then
    WAN4=$(sed -En 's/.*"(ip|query)":[ ]*"([^"]+)".*/\2/p' <<< "$IP_RESULT4")
    COUNTRY4=$(sed -En 's/.*"country":[ ]*"([^"]+)".*/\1/p' <<< "$IP_RESULT4")
    ASNORG4=$(sed -En 's/.*"(isp|asn_org)":[ ]*"([^"]+)".*/\2/p' <<< "$IP_RESULT4")
  fi
  
  local IP_RESULT6=$(curl --retry 2 -6 -ksm5 --user-agent Mozilla https://ifconfig.co/json 2>/dev/null)
  if [ -n "$IP_RESULT6" ]; then
    WAN6=$(sed -En 's/.*"(ip|query)":[ ]*"([^"]+)".*/\2/p' <<< "$IP_RESULT6")
    COUNTRY6=$(sed -En 's/.*"country":[ ]*"([^"]+)".*/\1/p' <<< "$IP_RESULT6")
    ASNORG6=$(sed -En 's/.*"(isp|asn_org)":[ ]*"([^"]+)".*/\2/p' <<< "$IP_RESULT6")
  fi
}

# 检查WireProxy状态
check_wireproxy_status() {
  if [ -x "$(type -p wireproxy)" ]; then
    if ss -nltp 2>/dev/null | awk '{print $NF}' | awk -F \" '{print $2}' | grep -q wireproxy; then
      WIREPROXY_STATUS="已开启"
      get_wireproxy_ip
    else
      WIREPROXY_STATUS="已安装，状态为断开连接"
    fi
  else
    WIREPROXY_STATUS="未安装"
  fi
}

# 检查Client状态
check_client_status() {
  if [ -x "$(type -p warp-cli)" ]; then
    local CLIENT_CONNECTED=$(warp-cli --accept-tos status 2>/dev/null | awk '/Status update/{for (i=0; i<NF; i++) if ($i=="update:") {print $(i+1)}}')
    if [ "$CLIENT_CONNECTED" = 'Connected' ]; then
      CLIENT_MODE=$(warp-cli --accept-tos settings 2>/dev/null | awk '/Mode:/{for (i=0; i<NF; i++) if ($i=="Mode:") {print $(i+1)}}')
      if [ "$CLIENT_MODE" = 'Warp' ]; then
        CLIENT_STATUS="已开启 (Warp全局模式)"
        # 对于全局模式，不使用端口
      elif [ "$CLIENT_MODE" = 'WarpProxy' ]; then
        CLIENT_STATUS="已开启 (Proxy模式)"
        get_client_ip
      else
        CLIENT_STATUS="已开启 (模式未知: $CLIENT_MODE)"
      fi
    else
      CLIENT_STATUS="已安装，断开状态"
    fi
  else
    CLIENT_STATUS="未安装"
  fi
}

# 显示系统信息
show_info() {
  clear
  echo "---------------------------------------------------------"
  info "版本:$VERSION"
  info "系统信息:"
  info "\t 当前操作系统:$SYS"
  info "\t 内核:$(uname -r)"
  info "\t 处理器架构:$(uname -m)"
  info "\t 虚拟化:$VIRT "
  info "\t IPv4: $WAN4 $COUNTRY4  $ASNORG4 "
  info "\t IPv6: $WAN6 $COUNTRY6  $ASNORG6 "
  
  # 显示WireProxy状态
  if [ "$WIREPROXY_STATUS" = "已开启" ]; then
    info "\t WARP Free WireProxy $WIREPROXY_STATUS\t 本地 Socks5: $WIREPROXY_SOCKS5"
    info "\t IPv4: $WIREPROXY_WAN4 $WIREPROXY_COUNTRY4 $WIREPROXY_ASNORG4"
    info "\t IPv6: $WIREPROXY_WAN6 $WIREPROXY_COUNTRY6 $WIREPROXY_ASNORG6 "
  else
    info "\t WireProxy $WIREPROXY_STATUS "
  fi
  
  # 显示Client状态  
  if [[ "$CLIENT_STATUS" =~ "已开启" ]]; then
    if [ "$CLIENT_MODE" = 'Warp' ]; then
      info "\t WARP Client $CLIENT_STATUS"
      # 全局模式下，获取 CloudflareWARP 接口IP
      if ip link show 2>/dev/null | grep -q CloudflareWARP; then
        info "\t 网络接口: CloudflareWARP (全局代理生效)"
      fi
    elif [ "$CLIENT_MODE" = 'WarpProxy' ]; then
      info "\t WARP Client $CLIENT_STATUS\t 本地 Socks5: $CLIENT_SOCKS5"
      info "\t IPv4: $CLIENT_WAN4 $CLIENT_COUNTRY4 $CLIENT_ASNORG4"
      info "\t IPv6: $CLIENT_WAN6 $CLIENT_COUNTRY6 $CLIENT_ASNORG6 "
    fi
  else
    info "\t WARP Client $CLIENT_STATUS "
  fi
  
  echo "---------------------------------------------------------"
}

# 检查端口是否被占用
check_port_conflict() {
  local PORT=$1
  local SERVICE_NAME=$2
  
  if ss -nltp 2>/dev/null | awk '{print $4}' | awk -F: '{print $NF}' | grep -qw "$PORT"; then
    local OCCUPIER=$(ss -nltp 2>/dev/null | grep ":$PORT" | awk '{print $NF}' | awk -F'"' '{print $2}' | head -n1)
    warning " ⚠ 端口 $PORT 已被占用 (占用者: ${OCCUPIER:-未知})"
    warning "   建议: 关闭占用端口的服务，或修改 $SERVICE_NAME 端口"
    return 1
  fi
  return 0
}

# 输入端口
input_port() {
  local SERVICE_TYPE=$1  # "wireproxy" 或 "client"
  local i=5
  local DEFAULT_PORT=40000
  
  # 检查默认端口
  if ss -nltp 2>/dev/null | awk '{print $4}' | awk -F: '{print $NF}' | grep -qw $DEFAULT_PORT; then
    warning " 默认端口 $DEFAULT_PORT 已被占用"
    reading " 请输入自定义端口 [1000-65535]: " PORT
  else
    reading " 请输入端口 (回车使用默认 $DEFAULT_PORT) [1000-65535]: " PORT
  fi
  
  PORT=${PORT:-$DEFAULT_PORT}
  
  # 验证端口
  until grep -qE "^[1-9][0-9]{3,4}$" <<< $PORT && [[ "$PORT" -ge 1000 && "$PORT" -le 65535 ]] && [[ ! $(ss -nltp 2>/dev/null) =~ :"$PORT"[[:space:]] ]]; do
    (( i-- )) || true
    [ "$i" = 0 ] && error " 输入错误达5次，脚本退出"
    
    if grep -qwE "^[1-9][0-9]{3,4}$" <<< $PORT; then
      if [[ "$PORT" -ge 1000 && "$PORT" -le 65535 ]]; then
        if ss -nltp 2>/dev/null | awk '{print $4}' | awk -F: '{print $NF}' | grep -qw $PORT; then
          warning " 端口 $PORT 已被占用"
          reading " 请重新输入端口 (剩余${i}次): " PORT
          PORT=${PORT:-$DEFAULT_PORT}
        fi
      else
        warning " 端口必须在 1000-65535 范围内"
        reading " 请重新输入 (剩余${i}次): " PORT
        PORT=${PORT:-$DEFAULT_PORT}
      fi
    else
      warning " 端口格式不正确"
      reading " 请输入有效端口 (剩余${i}次): " PORT
      PORT=${PORT:-$DEFAULT_PORT}
    fi
  done
}

# 修改 WireProxy 端口
change_wireproxy_port() {
  if [ ! -x "$(type -p wireproxy)" ]; then
    error " WireProxy 未安装"
  fi
  
  if [ ! -f "/etc/wireguard/proxy.conf" ]; then
    error " WireProxy 配置文件不存在: /etc/wireguard/proxy.conf"
  fi
  
  # 获取当前端口
  local CURRENT_PORT=$(grep "BindAddress" /etc/wireguard/proxy.conf 2>/dev/null | awk -F: '{print $NF}')
  info " 当前 WireProxy 端口: ${CURRENT_PORT:-未知}"
  
  # 输入新端口
  input_port "wireproxy"
  
  info " 正在修改 WireProxy 端口为: $PORT"
  
  # 停止服务
  if [ "$SYSTEM" = "Alpine" ]; then
    rc-service wireproxy stop >/dev/null 2>&1
  else
    systemctl stop wireproxy >/dev/null 2>&1
  fi
  
  # 修改配置
  sed -i "s/BindAddress.*/BindAddress = 127.0.0.1:$PORT/g" /etc/wireguard/proxy.conf
  
  # 启动服务
  if [ "$SYSTEM" = "Alpine" ]; then
    rc-service wireproxy start >/dev/null 2>&1
  else
    systemctl start wireproxy >/dev/null 2>&1
  fi
  
  sleep 2
  
  # 验证
  if ss -nltp 2>/dev/null | grep -q ":$PORT.*wireproxy"; then
    info " ✓ WireProxy 端口已成功修改为: $PORT"
    get_wireproxy_ip
    info " 新的 Socks5 地址: 127.0.0.1:$PORT"
  else
    error " ✗ 端口修改失败，请检查配置"
  fi
}

# 修改 Client 端口
change_client_port() {
  if [ ! -x "$(type -p warp-cli)" ]; then
    error " WARP Client 未安装"
  fi
  
  # 检查当前模式
  local CURRENT_MODE=$(warp-cli --accept-tos settings 2>/dev/null | awk '/Mode:/{for (i=0; i<NF; i++) if ($i=="Mode:") {print $(i+1)}}')
  
  if [ "$CURRENT_MODE" != "WarpProxy" ]; then
    warning " WARP Client 当前不在 Proxy 模式"
    warning " 端口修改仅在 Proxy 模式下有效"
    reading " 是否切换到 Proxy 模式? [y/N]: " SWITCH_MODE
    
    if [[ "${SWITCH_MODE,,}" == "y" ]]; then
      warp-cli --accept-tos mode proxy >/dev/null 2>&1
      sleep 1
    else
      info " 已取消"
      return 0
    fi
  fi
  
  # 获取当前端口
  local CURRENT_PORT=$(ss -nltp 2>/dev/null | awk '/"warp-svc"/{print $4}' | cut -d: -f2)
  info " 当前 WARP Client 端口: ${CURRENT_PORT:-未知}"
  
  # 输入新端口
  input_port "client"
  
  info " 正在修改 WARP Client 端口为: $PORT"
  warp-cli --accept-tos proxy port "$PORT" >/dev/null 2>&1
  sleep 2
  
  # 验证
  if ss -nltp 2>/dev/null | grep -q ":$PORT.*warp-svc"; then
    info " ✓ WARP Client 端口已成功修改为: $PORT"
    get_client_ip
    info " 新的 Socks5 地址: 127.0.0.1:$PORT"
  else
    error " ✗ 端口修改失败"
  fi
}

# 注册 WARP 账户（参考 menu.sh 的实现）
register_warp_account() {
  local LICENSE="$1"
  
  if [ -f /etc/wireguard/warp-account.conf ]; then
    info " 使用现有 WARP 账户"
    return 0
  fi
  
  info " 正在注册 WARP 免费账户..."
  
  # 生成 WireGuard 密钥对
  local PRIVATE_KEY=$(wg genkey)
  local PUBLIC_KEY=$(echo "$PRIVATE_KEY" | wg pubkey)
  
  # 调用 Cloudflare API 注册账户
  local REGISTER_RESPONSE=$(curl -s "https://api.cloudflareclient.com/v0a2158/reg" \
    -H "Content-Type: application/json" \
    -H "CF-Client-Version: a-6.30" \
    --data '{"key":"'"$PUBLIC_KEY"'","install_id":"","fcm_token":"","tos":"'"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)"'","type":"Android","locale":"en_US"}')
  
  if [ -n "$REGISTER_RESPONSE" ] && echo "$REGISTER_RESPONSE" | grep -q '"id"'; then
    echo "$REGISTER_RESPONSE" > /etc/wireguard/warp-account.conf
    info " ✓ WARP 账户注册成功"
    
    # 如果提供了 License，尝试升级到 WARP+
    if [ -n "$LICENSE" ]; then
      info " 正在升级到 WARP+ ..."
      local DEVICE_ID=$(echo "$REGISTER_RESPONSE" | grep -o '"id":"[^"]*' | cut -d'"' -f4)
      local TOKEN=$(echo "$REGISTER_RESPONSE" | grep -o '"token":"[^"]*' | cut -d'"' -f4)
      
      curl -s "https://api.cloudflareclient.com/v0a2158/reg/$DEVICE_ID/account" \
        -H "Authorization: Bearer $TOKEN" \
        -H "Content-Type: application/json" \
        --data '{"license":"'"$LICENSE"'"}' > /dev/null
      
      info " ✓ 已尝试升级到 WARP+"
    fi
  else
    warning " ⚠ 账户注册失败，使用预设免费账户"
    # 使用预设的免费账户（备用方案）
    cat > /etc/wireguard/warp-account.conf <<'EOF'
{"id":"317b5a76-3da1-469f-88d6-c3b261da9f10","account":{"id":"7e0e6c80-24c5-49ba-ba3d-087f45fcd1e9","account_type":"free","created":"0001-01-01T00:00:00Z","updated":"0001-01-01T00:00:00Z","license":"n01H3Cf4-3Za40C7b-5qOs0c42"},"config":{"client_id":"DuOi83pAIsbJMP3CJpxq6r3LVGHtqLlzybEIvbczRjo=","peers":[{"public_key":"bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=","endpoint":{"v4":"162.159.192.7:2408","v6":"[2606:4700:d0::a29f:c007]:2408","host":"engage.cloudflareclient.com:2408"}}],"interface":{"addresses":{"v4":"172.16.0.2/32","v6":"2606:4700:110:8d4e:cef9:30c2:6d4a:f97b/128"}}},"token":"11111111-1111-1111-1111-111111111111","warp_enabled":true,"waitlist_enabled":false,"created":"0001-01-01T00:00:00Z","updated":"0001-01-01T00:00:00Z","tos":"0001-01-01T00:00:00Z","place":0,"locale":"en_US","enabled":true,"install_id":"","fcm_token":""}
EOF
  fi
}

# 安装 WireProxy（基于 menu.sh 的简化实现）
install_wireproxy() {
  if [ -x "$(type -p wireproxy)" ]; then
    info " WireProxy 已安装"
    return 0
  fi

  info " 正在安装 WireProxy..."
  
  # 1. 安装必要依赖（简化版）
  if ! type -p wg > /dev/null; then
    info " 正在安装 wireguard-tools..."
    case "$SYSTEM" in
      Debian|Ubuntu)
        apt-get update > /dev/null 2>&1
        apt-get install -y wireguard-tools > /dev/null 2>&1
        ;;
      CentOS|Fedora)
        yum install -y wireguard-tools > /dev/null 2>&1
        ;;
      Alpine)
        apk add wireguard-tools > /dev/null 2>&1
        ;;
      Arch)
        pacman -S --noconfirm wireguard-tools > /dev/null 2>&1
        ;;
    esac
    [ -x "$(type -p wg)" ] && info " ✓ wireguard-tools 安装完成"
  fi
  
  # 2. 下载 WireProxy（参考 menu.sh 的方法）
  local ARCH=$(uname -m)
  [ "$ARCH" = "x86_64" ] && ARCH="amd64"
  [ "$ARCH" = "aarch64" ] && ARCH="arm64"
  
  info " 正在下载 WireProxy ($ARCH)..."
  local LATEST_VERSION=$(curl -s https://api.github.com/repos/pufferffish/wireproxy/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/' | head -1)
  LATEST_VERSION=${LATEST_VERSION:-1.0.9}
  
  curl -sL -o /tmp/wireproxy.tar.gz \
    "https://github.com/pufferffish/wireproxy/releases/download/v${LATEST_VERSION}/wireproxy_linux_${ARCH}.tar.gz" || \
  curl -sL -o /tmp/wireproxy.tar.gz \
    "https://gitlab.com/fscarmen/warp/-/raw/main/wireproxy/wireproxy_linux_${ARCH}.tar.gz"
  
  if [ $? -ne 0 ] || [ ! -f /tmp/wireproxy.tar.gz ]; then
    error " WireProxy 下载失败"
  fi
  
  tar -xzf /tmp/wireproxy.tar.gz -C /usr/bin/ 2>/dev/null
  chmod +x /usr/bin/wireproxy
  rm -f /tmp/wireproxy.tar.gz
  
  [ ! -x "$(type -p wireproxy)" ] && error " WireProxy 安装失败"
  info " ✓ WireProxy 安装完成"
  
  # 3. 注册 WARP 账户
  mkdir -p /etc/wireguard
  register_warp_account "$LICENSE"
  
  # 4. 生成配置文件（参考 menu.sh 的格式）
  info " 正在生成配置文件..."
  
  # 从账户信息中提取配置
  if [ -f /etc/wireguard/warp-account.conf ]; then
    local PRIVATE_KEY=$(grep -o '"private_key":"[^"]*' /etc/wireguard/warp-account.conf | cut -d'"' -f4 2>/dev/null)
    local IPV6_ADDR=$(grep -o '"v6":"[^"]*' /etc/wireguard/warp-account.conf | cut -d'"' -f4 | head -1)
    
    # 如果从账户文件解析失败，使用预设值
    [ -z "$PRIVATE_KEY" ] && PRIVATE_KEY=$(wg genkey)
    [ -z "$IPV6_ADDR" ] && IPV6_ADDR="2606:4700:110:8d4e:cef9:30c2:6d4a:f97b/128"
  else
    PRIVATE_KEY=$(wg genkey)
    IPV6_ADDR="2606:4700:110:8d4e:cef9:30c2:6d4a:f97b/128"
  fi
  
  # 生成 WireProxy 配置（参考 menu.sh，使用双 Address 行）
  cat > /etc/wireguard/proxy.conf <<EOF
[Interface]
Address = 172.16.0.2/32
Address = $IPV6_ADDR
MTU = 1280
PrivateKey = $PRIVATE_KEY
DNS = 1.1.1.1,8.8.8.8,8.8.4.4

[Peer]
PublicKey = bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
Endpoint = engage.cloudflareclient.com:2408

[Socks5]
BindAddress = 127.0.0.1:40000
EOF
  chmod 600 /etc/wireguard/proxy.conf
  info " ✓ 配置文件已生成"
  
  # 5. 创建 systemd 服务（参考 menu.sh 的实战配置）
  if [ "$SYSTEM" = "Alpine" ]; then
    cat > /etc/init.d/wireproxy <<'EOF'
#!/sbin/openrc-run

description="WireProxy for WARP"
command="/usr/bin/wireproxy"
command_args="-c /etc/wireguard/proxy.conf"
command_background=true
pidfile="/var/run/wireproxy.pid"
EOF
    chmod +x /etc/init.d/wireproxy
  else
    cat > /lib/systemd/system/wireproxy.service <<'EOF'
[Unit]
Description=WireProxy for WARP
After=network.target
Documentation=https://github.com/pufferffish/wireproxy

[Service]
ExecStart=/usr/bin/wireproxy -c /etc/wireguard/proxy.conf
RemainAfterExit=yes
Restart=always

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
  fi
  
  info " ✓ WireProxy 安装完成"
}

# 开启 WireProxy (Socks5代理)
enable_wireproxy() {
  if [ ! -x "$(type -p wireproxy)" ]; then
    warning " WireProxy 未安装，正在尝试自动安装..."
    install_wireproxy
  fi
  
  # 检查是否已经运行
  if ss -nltp 2>/dev/null | awk '{print $NF}' | awk -F \" '{print $2}' | grep -q wireproxy; then
    warning " WireProxy 已在运行中，无需重复启动"
    get_wireproxy_ip
    info " 当前 Socks5: $WIREPROXY_SOCKS5"
    return 0
  fi
  
  info " 正在启动 WireProxy Socks5 代理..."
  
  if [ "$SYSTEM" = "Alpine" ]; then
    rc-service wireproxy start >/dev/null 2>&1
  else
    systemctl start wireproxy >/dev/null 2>&1
  fi
  
  sleep 2
  
  if ss -nltp 2>/dev/null | awk '{print $NF}' | awk -F \" '{print $2}' | grep -q wireproxy; then
    get_wireproxy_ip
    info " ✓ WireProxy Socks5 代理已成功启动"
    info "   本地 Socks5: $WIREPROXY_SOCKS5"
    info "   IPv4: $WIREPROXY_WAN4 $WIREPROXY_COUNTRY4 $WIREPROXY_ASNORG4"
    info "   IPv6: $WIREPROXY_WAN6 $WIREPROXY_COUNTRY6 $WIREPROXY_ASNORG6"
  else
    error " ✗ WireProxy 启动失败，正在诊断问题..."
    
    # 检查配置文件
    if [ ! -f /etc/wireguard/proxy.conf ]; then
      error "   配置文件不存在: /etc/wireguard/proxy.conf"
    fi
    
    # 测试配置文件语法（尝试运行并捕获错误）
    warning "   尝试手动启动以查看错误信息:"
    timeout 3 /usr/bin/wireproxy -c /etc/wireguard/proxy.conf 2>&1 | head -20 | sed 's/^/   /'
    
    # 检查端口冲突
    local BIND_PORT=$(grep "BindAddress" /etc/wireguard/proxy.conf 2>/dev/null | awk -F: '{print $NF}')
    if [ -n "$BIND_PORT" ] && ss -nltp 2>/dev/null | grep -q ":$BIND_PORT"; then
      local OCCUPIER=$(ss -nltp 2>/dev/null | grep ":$BIND_PORT" | awk '{print $NF}' | awk -F'"' '{print $2}' | head -n1)
      error "   端口 $BIND_PORT 被占用: ${OCCUPIER:-未知进程}"
    fi
    
    # 显示 systemd 日志
    if [ "$SYSTEM" != "Alpine" ]; then
      warning "   systemd 日志 (最近20条):"
      journalctl -u wireproxy -n 20 --no-pager 2>/dev/null | sed 's/^/   /'
    fi
    
    exit 1
  fi
}

# 关闭 WireProxy (Socks5代理)
disable_wireproxy() {
  if [ ! -x "$(type -p wireproxy)" ]; then
    warning " WireProxy 未安装"
    return 1
  fi
  
  # 检查是否在运行
  if ! ss -nltp 2>/dev/null | awk '{print $NF}' | awk -F \" '{print $2}' | grep -q wireproxy; then
    warning " WireProxy 未在运行"
    return 0
  fi
  
  info " 正在关闭 WireProxy Socks5 代理..."
  
  if [ "$SYSTEM" = "Alpine" ]; then
    rc-service wireproxy stop >/dev/null 2>&1
  else
    systemctl stop wireproxy >/dev/null 2>&1
  fi
  
  sleep 1
  
  if ! ss -nltp 2>/dev/null | awk '{print $NF}' | awk -F \" '{print $2}' | grep -q wireproxy; then
    info " ✓ WireProxy Socks5 代理已关闭"
  else
    warning " ✗ WireProxy 关闭失败"
  fi
}

# 安装 WARP Client
install_warp_client() {
  if [ -x "$(type -p warp-cli)" ]; then
    info " WARP Client 已安装"
    return 0
  fi

  info " 正在安装 WARP Client..."
  
  if [ "$SYSTEM" = "Debian" ] || [ "$SYSTEM" = "Ubuntu" ]; then
    # 添加 GPG key
    curl https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
    
    # 添加源
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/cloudflare-client.list
    
    # 更新并安装
    apt-get update && apt-get install -y cloudflare-warp
    
  elif [ "$SYSTEM" = "CentOS" ] || [ "$SYSTEM" = "Fedora" ]; then
    # 添加源
    curl -fsSL https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo | tee /etc/yum.repos.d/cloudflare-warp.repo
    
    # 安装
    yum install -y cloudflare-warp
    
  else
    error " 暂不支持自动安装 WARP Client 的系统: $SYSTEM"
  fi
  
  if [ -x "$(type -p warp-cli)" ]; then
    info " ✓ WARP Client 安装完成"
  else
    error " WARP Client 安装失败"
  fi
}

# 开启 Client 全局代理
enable_client_global() {
  if [ ! -x "$(type -p warp-cli)" ]; then
    warning " WARP Client 未安装，正在尝试自动安装..."
    install_warp_client
  fi
  
  # 检查连接状态
  local CLIENT_CONNECTED=$(warp-cli --accept-tos status 2>/dev/null | awk '/Status update/{for (i=0; i<NF; i++) if ($i=="update:") {print $(i+1)}}')
  local CURRENT_MODE=$(warp-cli --accept-tos settings 2>/dev/null | awk '/Mode:/{for (i=0; i<NF; i++) if ($i=="Mode:") {print $(i+1)}}')
  
  # 如果已连接且是Warp模式
  if [ "$CLIENT_CONNECTED" = 'Connected' ] && [ "$CURRENT_MODE" = 'Warp' ]; then
    warning " WARP Client 全局代理已在运行中"
    return 0
  fi
  
  info " 正在启动 WARP Client 全局代理..."
  
  # 如果当前是Proxy模式，需要先断开
  if [ "$CURRENT_MODE" = "WarpProxy" ]; then
    hint " 检测到当前为 Proxy 模式，正在切换到 Warp 全局模式..."
    warp-cli --accept-tos disconnect >/dev/null 2>&1
    sleep 1
  fi
  
  # 设置为 Warp 模式
  info " 设置为 WARP 全局模式..."
  warp-cli --accept-tos mode warp >/dev/null 2>&1
  sleep 1
  
  # 连接
  hint " 正在连接 WARP..."
  warp-cli --accept-tos connect >/dev/null 2>&1
  sleep 3
  
  local CLIENT_CONNECTED=$(warp-cli --accept-tos status 2>/dev/null | awk '/Status update/{for (i=0; i<NF; i++) if ($i=="update:") {print $(i+1)}}')
  if [ "$CLIENT_CONNECTED" = 'Connected' ]; then
    info " ✓ WARP Client 全局代理已成功启动"
    
    # 检查网络接口
    if ip link show 2>/dev/null | grep -q CloudflareWARP; then
      info " ✓ CloudflareWARP 网络接口已创建"
      info " 所有网络流量现在通过 WARP"
    else
      warning " ⚠ CloudflareWARP 接口未检测到，可能需要等待几秒"
    fi
  else
    error " ✗ WARP Client 连接失败，请检查配置"
  fi
}

# 关闭 Client 全局代理
disable_client_global() {
  if [ ! -x "$(type -p warp-cli)" ]; then
    warning " WARP Client 未安装"
    return 1
  fi
  
  local CLIENT_CONNECTED=$(warp-cli --accept-tos status 2>/dev/null | awk '/Status update/{for (i=0; i<NF; i++) if ($i=="update:") {print $(i+1)}}')
  
  if [ "$CLIENT_CONNECTED" != 'Connected' ]; then
    warning " WARP Client 未在运行"
    return 0
  fi
  
  info " 正在关闭 WARP Client 全局代理..."
  
  warp-cli --accept-tos disconnect >/dev/null 2>&1
  sleep 1
  
  local CLIENT_CONNECTED=$(warp-cli --accept-tos status 2>/dev/null | awk '/Status update/{for (i=0; i<NF; i++) if ($i=="update:") {print $(i+1)}}')
  if [ "$CLIENT_CONNECTED" != 'Connected' ]; then
    info " ✓ WARP Client 全局代理已关闭"
  else
    warning " ✗ WARP Client 关闭失败"
  fi
}

# 卸载功能
uninstall() {
  warning " 警告: 此操作将卸载 WireProxy 和 WARP Client"
  reading " 确认卸载请按 [y]，其他键取消: " CONFIRM
  
  if [[ "${CONFIRM,,}" != 'y' ]]; then
    info " 已取消卸载"
    return 0
  fi
  
  info " 开始卸载..."
  
  # 卸载 WireProxy
  if [ -x "$(type -p wireproxy)" ]; then
    info " 正在卸载 WireProxy..."
    if [ "$SYSTEM" = "Alpine" ]; then
      rc-update del wireproxy default >/dev/null 2>&1
      rc-service wireproxy stop >/dev/null 2>&1
      rm -f /etc/init.d/wireproxy
    else
      systemctl disable --now wireproxy >/dev/null 2>&1
    fi
    rm -rf /usr/bin/wireproxy /lib/systemd/system/wireproxy.service /etc/wireguard/proxy.conf
    info " ✓ WireProxy 卸载完成"
  fi
  
  # 卸载 WARP Client
  if [ -x "$(type -p warp-cli)" ]; then
    info " 正在卸载 WARP Client..."
    warp-cli --accept-tos disconnect >/dev/null 2>&1
    warp-cli --accept-tos delete >/dev/null 2>&1
    
    if [ "$SYSTEM" = "Debian" ] || [ "$SYSTEM" = "Ubuntu" ]; then
      apt-get purge -y cloudflare-warp >/dev/null 2>&1
      rm -f /etc/apt/sources.list.d/cloudflare-client.list
      rm -f /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
    elif [ "$SYSTEM" = "CentOS" ] || [ "$SYSTEM" = "Fedora" ]; then
      yum remove -y cloudflare-warp >/dev/null 2>&1
    fi
    info " ✓ WARP Client 卸载完成"
  fi
  
  # 清理配置文件
  info " 清理配置文件..."
  rm -rf /etc/wireguard/warp-account.conf /etc/wireguard/info.log
  [[ -e /etc/wireguard && -z "$(ls -A /etc/wireguard/)" ]] && rmdir /etc/wireguard
  
  info " ✓ 卸载完成"
}

# 显示菜单
show_menu() {
  # 更新状态信息
  get_native_ip
  check_wireproxy_status
  check_client_status
  
  show_info
  
  hint " 1）开启 WireProxy Socks5 代理"
  hint " 2）开启 WARP Client 全局代理"
  hint " 3）关闭 WireProxy Socks5 代理"
  hint " 4）关闭 WARP Client 全局代理"
  hint " 5）修改 WireProxy Socks5 端口"
  hint " 6）卸载"
  hint " 0）退出"
  reading " 请选择: " CHOICE
  
  case "$CHOICE" in
    1)
      enable_wireproxy
      ;;
    2)
      enable_client_global
      ;;
    3)
      disable_wireproxy
      ;;
    4)
      disable_client_global
      ;;
    5)
      # 端口修改子菜单
      hint "\n 选择要修改端口的服务:"
      hint " 1) WireProxy"
      hint " 2) WARP Client"
      hint " 0) 返回"
      reading " 请选择: " PORT_CHOICE
      case "$PORT_CHOICE" in
        1) change_wireproxy_port ;;
        2) change_client_port ;;
        0) show_menu ;;
        *) warning " 无效选择"; sleep 1; show_menu ;;
      esac
      ;;
    6)
      uninstall
      ;;
    0)
      info " 退出脚本"
      exit 0
      ;;
    *)
      warning " 请输入正确数字 [0-6]"
      sleep 1
      show_menu
      ;;
  esac
  
  echo ""
  reading " 按回车键继续..." DUMMY
  show_menu
}

# 主程序
main() {
  check_root
  check_operating_system
  check_virt "$SYSTEM"
  
  # 命令行参数处理
  case "$1" in
    -s)
      # 开启 warp socket5代理
      get_native_ip
      check_wireproxy_status
      enable_wireproxy
      ;;
    -w)
      # 开启 warp全局代理
      get_native_ip
      check_client_status
      enable_client_global
      ;;
    -cs)
      # 关闭 warp socket5代理
      disable_wireproxy
      ;;
    -cw)
      # 关闭 warp全局代理
      disable_client_global
      ;;
    -u)
      # 卸载
      uninstall
      ;;
    -p)
      # 修改端口（隐藏功能）
      if [ "$2" = "wireproxy" ]; then
        change_wireproxy_port
      elif [ "$2" = "client" ]; then
        change_client_port
      else
        info " 用法: $0 -p [wireproxy|client]"
      fi
      ;;
    -h|--help)
      info " ax-warpsocket5.sh v$VERSION - WARP 代理管理脚本"
      info ""
      info " 用法:"
      info "   $0           # 显示交互菜单"
      info "   $0 -s        # 开启 WireProxy Socks5 代理"
      info "   $0 -w        # 开启 WARP Client 全局代理"
      info "   $0 -cs       # 关闭 WireProxy Socks5 代理"
      info "   $0 -cw       # 关闭 WARP Client 全局代理"
      info "   $0 -p wireproxy  # 修改 WireProxy 端口"
      info "   $0 -p client     # 修改 Client 端口"
      info "   $0 -u        # 卸载所有组件"
      ;;
    *)
      # 默认显示菜单
      show_menu
      ;;
  esac
}

# 运行主程序
main "$@"
