#!/bin/bash
# 一键开启 warp socket5，支持端口修改。
# Generated by github.com/halibotee

SCRIPT_VERSION="1.0.0"

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export LANG=en_US.UTF-8
endpoint=
red='\033[0;31m'
bblue='\033[0;34m'
yellow='\033[0;33m'
green='\033[0;32m'
plain='\033[0m'
red(){ echo -e "\033[31m\033[01m$1\033[0m";}
green(){ echo -e "\033[32m\033[01m$1\033[0m";}
yellow(){ echo -e "\033[33m\033[01m$1\033[0m";}
blue(){ echo -e "\033[36m\033[01m$1\033[0m";}
white(){ echo -e "\033[37m\033[01m$1\033[0m";}
bblue(){ echo -e "\033[34m\033[01m$1\033[0m";}
rred(){ echo -e "\033[35m\033[01m$1\033[0m";}
readtp(){ read -t5 -n26 -p "$(yellow "$1")" $2;}
readp(){ read -p "$(yellow "$1")" $2;}


# --- [新增] 日志文件定义 ---
FULL_LOG_FILE="/var/log/cfwarp_socks5.log"
ERROR_LOG_FILE="/var/log/cfwarp_socks5.error.log"
LOG_LIMIT_BYTES=1048576 # 1MB



[[ $EUID -ne 0 ]] && yellow "请以root模式运行脚本" && exit



# --- [新增] 系统资源检查函数 ---
check_system_resources() {
    yellow "正在检查系统资源..."
    
    # 检查可用内存（单位：MB）
    local free_mem=$(free -m 2>/dev/null | awk 'NR==2{print $7}')
    if [[ -z "$free_mem" ]]; then
        # 兼容旧版 free 命令
        free_mem=$(free -m 2>/dev/null | awk 'NR==2{print $4}')
    fi
    
    if [[ -n "$free_mem" ]]; then
        if [[ $free_mem -lt 100 ]]; then
            red "⚠ 警告: 可用内存仅 ${free_mem}MB，低于建议值 100MB"
            yellow "  这可能导致安装过程中系统卡顿或假死机"
            readp "  是否继续安装？[y/N]: " continue_install
            [[ ! "$continue_install" =~ ^[Yy]$ ]] && yellow "已取消安装" && return 1
        else
            green "✓ 可用内存: ${free_mem}MB (充足)"
        fi
    fi
    
    # 检查磁盘空间
    local free_disk=$(df -m / | awk 'NR==2{print $4}')
    if [[ -n "$free_disk" && $free_disk -lt 200 ]]; then
        yellow "⚠ 警告: 根目录可用空间仅 ${free_disk}MB"
    fi
    
    return 0
}

if [[ -f /etc/redhat-release ]]; then
release="Centos"
elif cat /etc/issue | grep -q -E -i "debian"; then
release="Debian"
elif cat /etc/issue | grep -q -E -i "ubuntu"; then
release="Ubuntu"
elif cat /etc/issue | grep -q -E -i "centos|red hat|redhat"; then
release="Centos"
elif cat /proc/version | grep -q -E -i "debian"; then
release="Debian"
elif cat /proc/version | grep -q -E -i "ubuntu"; then
release="Ubuntu"
elif cat /proc/version | grep -q -E -i "centos|red hat|redhat"; then
release="Centos"
else 
red "不支持当前的系统，请选择使用Ubuntu,Debian,Centos系统。" && exit
fi
vsid=$(grep -i version_id /etc/os-release | cut -d \" -f2 | cut -d . -f1)
op=$(cat /etc/redhat-release 2>/dev/null || cat /etc/os-release 2>/dev/null | grep -i pretty_name | cut -d \" -f2)
version=$(uname -r | cut -d "-" -f1)
main=$(uname -r | cut -d "." -f1)
minor=$(uname -r | cut -d "." -f2)
vi=$(systemd-detect-virt)
case "$release" in
"Centos") yumapt='yum -y';;
"Ubuntu"|"Debian") yumapt="apt-get -y";;
esac
cpujg(){
case $(uname -m) in
aarch64) cpu=arm64;;
x86_64) cpu=amd64;;
*) red "目前脚本不支持$(uname -m)架构" && exit;;
esac
}

nf4(){
UA_Browser="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
result=$(curl -4fsL --user-agent "${UA_Browser}" --write-out %{http_code} --output /dev/null --max-time 10 "https://www.netflix.com/title/70143836" 2>&1)
if [[ "$result" == "404" ]]; then 
NF="遗憾，当前IP仅解锁Netflix自制剧"
elif [[ "$result" == "403" ]]; then
NF="杯具，当前IP不能看Netflix"
elif [[ "$result" == "200" ]]; then
NF="恭喜，当前IP完整解锁Netflix非自制剧"
else
NF="死心吧，Netflix不服务当前IP地区"
fi
}

nf6(){
UA_Browser="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
result=$(curl -6fsL --user-agent "${UA_Browser}" --write-out %{http_code} --output /dev/null --max-time 10 "https://www.netflix.com/title/70143836" 2>&1)
if [[ "$result" == "404" ]]; then 
NF="遗憾，当前IP仅解锁Netflix自制剧"
elif [[ "$result" == "403" ]]; then
NF="杯具，当前IP不能看Netflix"
elif [[ "$result" == "200" ]]; then
NF="恭喜，当前IP完整解锁Netflix非自制剧"
else
NF="死心吧，Netflix不服务当前IP地区"
fi
}

nfs5() {
UA_Browser="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36"
result=$(curl --user-agent "${UA_Browser}" --write-out %{http_code} --output /dev/null --max-time 10 -sx socks5h://localhost:$mport -4sL "https://www.netflix.com/title/70143836" 2>&1)
if [[ "$result" == "404" ]]; then 
NF="遗憾，当前IP仅解锁Netflix自制剧"
elif [[ "$result" == "403" ]]; then
NF="杯具，当前IP不能看Netflix"
elif [[ "$result" == "200" ]]; then
NF="恭喜，当前IP完整解锁Netflix非自制剧"
else
NF="死心吧，Netflix不服务当前IP地区"
fi
}

v4v6(){
v4=$(curl -s4m5 icanhazip.com -k)
v6=$(curl -s6m5 icanhazip.com -k)
}

warpip(){
mkdir -p /root/warpip
v4v6
if [[ -z $v4 ]]; then
endpoint=[2606:4700:d0::a29f:c001]:2408
else
endpoint=162.159.192.1:2408
fi
}

restwarpgo(){
# 保留此函数仅用于 SOCKS5ins 中的冲突检查
kill -15 $(pgrep warp-go) >/dev/null 2>&1 && sleep 2
systemctl restart warp-go >/dev/null 2>&1
systemctl enable warp-go >/dev/null 2>&1
systemctl start warp-go >/dev/null 2>&1
}

chatgpt4(){
gpt1=$(curl -s4 https://chat.openai.com 2>&1)
gpt2=$(curl -s4 https://ios.chat.openai.com 2>&1)
}
chatgpt6(){
gpt1=$(curl -s6 https://chat.openai.com 2>&1)
gpt2=$(curl -s6 https://ios.chat.openai.com 2>&1)
}
checkgpt(){
if [[ $gpt2 == *VPN* ]]; then
chat='遗憾，当前IP仅解锁ChatGPT网页，未解锁客户端'
elif [[ $gpt2 == *Request* ]]; then
chat='恭喜，当前IP完整解锁ChatGPT (网页+客户端)'
else
chat='杯具，当前IP无法解锁ChatGPT服务'
fi
}

checkgemini(){
if echo "$gemini_raw" | grep -q "not available in your country" || echo "$gemini_raw" | grep -q "unavailable in your region"; then
    gemini='杯具，当前IP地区不可用'
elif [[ -n "$gemini_raw" ]]; then
    gemini='恭喜，可访问Gemini'
else
    gemini='检测失败 (超时或连接错误)'
fi
}

# --- [修改] ShowSOCKS5 函数, 移除日志提示 ---
ShowSOCKS5(){
    blue " 脚本版本: $(green "$SCRIPT_VERSION")"
    
    if [[ $(systemctl is-active warp-svc) = active ]]; then
        mport=`warp-cli --accept-tos settings 2>/dev/null | grep 'WarpProxy on port' | awk -F "port " '{print $2}'`
        
        # --- [v1.3.4 修复] 增加 --max-time 5 ---
        # 检查SOCKS5是否真的在工作
        socks5=$(curl -sx socks5h://localhost:$mport www.cloudflare.com/cdn-cgi/trace -k --connect-timeout 4 --max-time 5 | grep warp | cut -d= -f2) 
        
        if [[ $socks5 =~ on|plus ]]; then
            s5ip=`curl -sx socks5h://localhost:$mport icanhazip.com -k --max-time 5`
            nfs5 # nfs5 函数内部自带 --max-time 10
            
            # --- [Bug B 修复] 增加 --max-time 5 ---
            gpt1=$(curl -sx socks5h://localhost:$mport --max-time 5 https://chat.openai.com 2>&1)
            gpt2=$(curl -sx socks5h://localhost:$mport --max-time 5 https://android.chat.openai.com 2>&1)
            checkgpt
            
            gemini_raw=$(curl -sx socks5h://localhost:$mport -sL --user-agent "${UA_Browser}" --max-time 5 https://gemini.google.com/ 2>&1)
            checkgemini
            
            # --- [Bug B 修复] 增加 --max-time 5 ---
            nonf=$(curl -sx socks5h://localhost:$mport --user-agent "${UA_Browser}" --max-time 5 http://ip-api.com/json/$s5ip?lang=zh-CN -k | cut -f2 -d"," | cut -f4 -d '"')
            country=$nonf

            if [[ $socks5 = plus ]]; then
                echo -e " $(blue "Socks5 WARP+状态：") $(rred "运行中 (WARP+账户)")"
                echo -e " $(blue "剩余WARP+流量：") $(rred "$((`warp-cli --accept-tos account | grep Quota | awk '{ print $(NF) }'`/1000000000)) GB")"
            else
                echo -e " $(blue "Socks5 WARP状态：") $(green "运行中 (WARP普通账户)")"
            fi
            
            echo -e " $(blue "Socks5 端口：") $(green "$mport")"
            echo -e " $(blue "Cloudflare IPV4：") $(green "$s5ip  $country")"
            echo -e " $(blue "奈飞NF解锁：") $(green "$NF")"
            echo -e " $(blue "ChatGPT解锁：") $(green "$chat")"
            echo -e " $(blue "Gemini解锁：") $(green "$gemini")"

        else
            echo -e " $(blue "Socks5 WARP状态：") $(yellow "已安装，但Socks5代理连接失败 (端口: $mport)")"
        fi
    else
        echo -e " $(blue "Socks5 WARP状态：") $(red "未安装或服务未运行")"
    fi
    
    # --- [v1.3.7 修复] 移除所有日志提示和分隔线 ---
}


cso(){
warp-cli --accept-tos disconnect >/dev/null 2>&1
warp-cli --accept-tos disable-always-on >/dev/null 2>&1
warp-cli --accept-tos delete >/dev/null 2>&1
if [[ $release = Centos ]]; then
yum autoremove cloudflare-warp -y
else
apt purge cloudflare-warp -y
rm -f /etc/apt/sources.list.d/cloudflare-client.list /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
fi
$yumapt autoremove
green "Socks5-WARP 卸载完成。"
}

# --- [重大修复] v1.3.5 端口修改 Bug 修复 ---
SOCKS5WARPPORT(){
[[ ! $(type -P warp-cli) ]] && red "未安装Socks5-WARP，无法更改端口" && return 1
readp "请输入自定义socks5端口[2000～65535]（回车跳过为2000-65535之间的随机端口）:" port
if [[ -z $port ]]; then
port=$(shuf -i 2000-65535 -n 1)
until [[ -z $(ss -ntlp | awk '{print $4}' | sed 's/.*://g' | grep -w "$port") ]]
do
[[ -n $(ss -ntlp | awk '{print $4}' | sed 's/.*://g' | grep -w "$port") ]] && yellow "\n端口被占用，请重新输入端口" && readp "自定义socks5端口:" port
done
else
until [[ -z $(ss -ntlp | awk '{print $4}' | sed 's/.*://g' | grep -w "$port") ]]
do
[[ -n $(ss -ntlp | awk '{print $4}' | sed 's/.*://g' | grep -w "$port") ]] && yellow "\n端口被占用，请重新输入端口" && readp "自定义socks5端口:" port
done
fi

if [[ -n $port ]]; then
    green "新端口设置成功：$port"
    yellow "正在应用新端口 (约 5 秒)..."
    
    # [v1.3.3 修复方案] 采纳 menu.sh 逻辑, 使用正确的 'proxy port' 命令
    # 1. (服务运行时) 修改配置
    warp-cli --accept-tos proxy port $port
    
    # [v1.3.5 修复] 延长等待时间, 确保服务热加载完成
    sleep 5
    
    green "服务已自动应用新端口。"
else
    red "端口设置失败。"
fi
}

install_socks5(){
    # 0. 系统资源检查
    check_system_resources || return 1
    
    # 1. 检查状态
    yellow "正在检查 Cloudflare WARP Socks5 (warp-cli) 状态..."
    if [[ $(systemctl is-active warp-svc) = active ]] && [[ $(warp-cli --accept-tos status 2>/dev/null) =~ 'Connected' ]]; then
        green "Socks5-WARP 已在运行中。无需重复安装。"
        return 0
    fi

    # 2. 检查环境
    yellow "检测Socks5-WARP安装环境中……"
    if [[ $release = Centos ]]; then
    [[ ! ${vsid} =~ 8 ]] && yellow "当前系统版本号：Centos $vsid \nSocks5-WARP仅支持Centos 8 " && return 1
    elif [[ $release = Ubuntu ]]; then
    [[ ! ${vsid} =~ 20|22|24 ]] && yellow "当前系统版本号：Ubuntu $vsid \nSocks5-WARP仅支持 Ubuntu 20.04/22.04/24.04系统 " && return 1
    elif [[ $release = Debian ]]; then
    [[ ! ${vsid} =~ 10|11|12|13 ]] && yellow "当前系统版本号：Debian $vsid \nSocks5-WARP仅支持 Debian 10/11/12/13系统 " && return 1
    fi

    # 3. 冲突检查
    yellow "正在检查服务冲突..."
    systemctl stop wg-quick@wgcf >/dev/null 2>&1
    kill -15 $(pgrep warp-go) >/dev/null 2>&1 && sleep 2
    
    v4v6
    if [[ -n $v6 && -z $v4 ]]; then
    systemctl start wg-quick@wgcf >/dev/null 2>&1
    restwarpgo
    red "纯IPV6的VPS目前不支持安装Socks5-WARP" && sleep 2 && return 1
    else
    systemctl start wg-quick@wgcf >/dev/null 2>&1
    restwarpgo
    fi

    # 4. 开始安装
    yellow "正在执行一键安装/启动 Socks5-WARP..."
    yellow "⚠ 提示: 如果您通过 SSH 连接，建议在 screen/tmux 会话中运行"
    
    if [[ $release = Centos ]]; then 
    yellow "正在安装依赖 (epel-release, net-tools)..."
    timeout 120 yum -y install epel-release && timeout 120 yum -y install net-tools || {
        red "依赖安装超时或失败"
        return 1
    }
    curl -fsSl https://pkg.cloudflareclient.com/cloudflare-warp-ascii.repo | tee /etc/yum.repos.d/cloudflare-warp.repo
    yellow "正在更新软件源 (添加超时保护)..."
    timeout 180 yum update --exclude=kernel* || yellow "! yum update 超时，继续安装"
    yellow "正在安装 cloudflare-warp..."
    timeout 300 yum -y install cloudflare-warp || {
        red "cloudflare-warp 安装失败或超时"
        return 1
    }
    fi
    if [[ $release = Debian ]]; then
    [[ ! $(type -P gpg) ]] && timeout 120 apt update && timeout 120 apt install gnupg -y
    [[ ! $(apt list 2>/dev/null | grep apt-transport-https | grep installed) ]] && timeout 120 apt update && timeout 120 apt install apt-transport-https -y
    fi
    if [[ $release != Centos ]]; then 
    yellow "正在安装依赖..."
    timeout 120 apt install net-tools -y || yellow "! net-tools 安装超时"
    curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
    # --- [修改] 添加超时和防止升级内核 ---
   # yellow "正在更新软件源 (添加超时保护)..."
   # timeout 180 sudo apt-get update || yellow "! apt update 超时，继续安装"
    yellow "正在安装 cloudflare-warp (不升级系统包)..."
    timeout 300 sudo apt-get install -y --no-upgrade cloudflare-warp || {
        red "cloudflare-warp 安装失败或超时"
        return 1
    }
    fi
    
    # 5. 配置
    warpip
    yellow "正在自动注册新账户 (--accept-tos)..."
    warp-cli --accept-tos registration new
    
    # 强制设置为仅代理模式，防止修改全局路由
    yellow "正在配置为纯代理模式 (不修改系统路由)..."
    warp-cli mode proxy
    warp-cli proxy port 40000
    
    # --- [新增] 验证模式设置 ---
    local current_mode=$(warp-cli --accept-tos settings 2>/dev/null | grep 'Mode' | awk '{print $NF}')
    if [[ "$current_mode" != "Proxy" ]]; then
        yellow "! 警告: WARP 模式未正确设置为 Proxy，当前为: $current_mode"
        yellow "  尝试再次设置..."
        warp-cli mode proxy
        sleep 2
    fi
    
    yellow "正在连接 WARP (仅启用 SOCKS5 代理)..."
    warp-cli --accept-tos connect
    
    yellow "正在等待连接稳定 (8 秒)..."
    sleep 8
    
    # 6. 确认
    if [[ $(systemctl is-active warp-svc) = active ]] && [[ $(warp-cli --accept-tos status 2>/dev/null) =~ 'Connected' ]]; then
        green "✓ Socks5-WARP 已成功启动 (仅代理模式)"
        green "✓ SSH 连接应该未受影响"
    else
        red "✗ Socks5-WARP 安装或启动失败。请检查日志。"
    fi
}

checkyl(){
if [ ! -f warp_update ]; then
green "首次运行，安装必要的依赖……请稍等"
if [[ $release = Centos && ${vsid} =~ 8 ]]; then
cd /etc/yum.repos.d/ && mkdir backup && mv *repo backup/ 
curl -o /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-8.repo
sed -i -e "s|mirrors.cloud.aliyuncs.com|mirrors.aliyun.com|g " /etc/yum.repos.d/CentOS-*
sed -i -e "s|releasever|releasever-stream|g" /etc/yum.repos.d/CentOS-*
yum clean all && yum makecache
cd
fi
if [ -x "$(command -v apt-get)" ]; then
apt update -y && apt install curl wget -y
elif [ -x "$(command -v yum)" ]; then
yum update && yum install epel-release -y && yum install curl wget -y
elif [ -x "$(command -v dnf)" ]; then
dnf update -y && dnf install curl wget -y
fi
if [ -x "$(command -v yum)" ] || [ -x "$(command -v dnf)" ]; then
if ! command -v "cronie" &> /dev/null; then
if [ -x "$(command -v yum)" ]; then
yum install -y cronie
elif [ -x "$(command -v dnf)" ]; then
dnf install -y cronie
fi
fi
fi
touch warp_update
fi
}

warpyl(){
if [[ $release = Centos ]]; then
    packages=("curl" "openssl" "bc" "python3" "screen" "qrencode" "wget" "ss")
    inspackages=("curl" "openssl" "bc" "python3" "screen" "qrencode" "wget" "net-tools")
else
    packages=("curl" "openssl" "bc" "python3" "screen" "qrencode" "wget" "ss")
    inspackages=("curl" "openssl" "bc" "python3" "screen" "qrencode" "wget" "iproute2")
fi

for i in "${!packages[@]}"; do
package="${packages[$i]}"
inspackage="${inspackages[i]}"
if ! command -v "$package" &> /dev/null; then
if [ -x "$(command -v apt-get)" ]; then
apt-get install -y "$inspackage"
elif [ -x "$(command -v yum)" ]; then
yum install -y "$inspackage"
elif [ -x "$(command -v dnf)" ]; then
dnf install -y "$inspackage"
fi
fi
done
}

main_menu() {
    while true; do
        clear
        green "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        bblue " CFwarp Socks5 (warp-cli) 管理脚本"
        green "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
        
        echo
        ShowSOCKS5
        blue "------------------------------------------------------------------------------------------------"
        echo
        
        # 菜单选项
        green " 1. 安装/启动 Socks5-WARP"
        green " 2. 修改 Socks5 端口"
        red   " 3. 卸载 Socks5-WARP"
        echo
        green " 0. 退出脚本"
        echo
        
        readp " 请输入数字 [0-3]: " choice
        
        case "$choice" in
            1)
                install_socks5
                readp "操作完成。按 [Enter] 键返回菜单..."
                ;;
            2)
                SOCKS5WARPPORT
                readp "操作完成。按 [Enter] 键返回菜单..."
                ;;
            3)
                cso
                readp "操作完成。按 [Enter] 键返回菜单..."
                ;;
            0)
                exit 0
                ;;
            *)
                red "输入错误，请重新输入。"
                sleep 1
                ;;
        esac
    done
}

# --- [新增] 脚本主包裹函数 (用于日志捕获) ---
script_main_wrapper() {
    # --- [修改] v1.3.1 日志生命周期管理 ---
    
    # 1. 完整日志: 始终删除重建
    rm -f "$FULL_LOG_FILE"
    echo "CFwarp v$SCRIPT_VERSION - 完整日志 - 开始于: $(date)" >> "$FULL_LOG_FILE"

    # 2. 错误日志: 检查并截断 (Log Rotation)
    if [ -f "$ERROR_LOG_FILE" ]; then
        # 尝试获取文件大小
        local current_size=$(stat -c%s "$ERROR_LOG_FILE" 2>/dev/null)
        if [ -z "$current_size" ]; then
             current_size=0
        fi

        if [ "$current_size" -gt "$LOG_LIMIT_BYTES" ]; then
            echo "--- (错误日志超过 1MB，正在截断...) ---" >> "$FULL_LOG_FILE"
            # 使用 tail 截断, -c $LOG_LIMIT_BYTES 获取最后 1MB
            # 创建临时文件，移动，以保证原子性
            tail -c $LOG_LIMIT_BYTES "$ERROR_LOG_FILE" > "$ERROR_LOG_FILE.tmp" && mv "$ERROR_LOG_FILE.tmp" "$ERROR_LOG_FILE"
            echo "--- (日志已截断于 $(date)) ---" >> "$ERROR_LOG_FILE"
        fi
    fi
    # 每次会话都在错误日志中追加一个时间戳
    echo "CFwarp v$SCRIPT_VERSION - 错误日志 - 会话开始于: $(date)" >> "$ERROR_LOG_FILE"

    # 3. 运行主程序
    checkyl
    warpyl
    cpujg
    main_menu
}

script_main_wrapper 2>&1 | tee -a "$FULL_LOG_FILE"
