dnsconf:
    - name: ""
      ipv4:
        enable: true
        gettype: url
        url: https://myip.ipip.net, https://ddns.oray.com/checkip, https://ip.3322.net, https://4.ipw.cn, https://v4.yinghualuo.cn/bejson
        netinterface: eth0
        cmd: ""
        domains:
            - adh.xshine.top
      ipv6:
        enable: false
        gettype: netInterface
        url: https://speed.neu6.edu.cn/getIP.php, https://v6.ident.me, https://6.ipw.cn, https://v6.yinghualuo.cn/bejson
        netinterface: ""
        cmd: ""
        ipv6reg: ""
        domains:
            - ""
      dns:
        name: cloudflare
        id: ""
        secret: __CLOUDFLARE_API_TOKEN__
      ttl: ""
user:
    username: admin
    password: $2a$10$vgpDW5ZyPLxqyxhTOkGPpeL8rMgiuYkZyIyPkR7Kwfalezd.sLrZe
webhook:
    webhookurl: ""
    webhookrequestbody: ""
    webhookheaders: ""
notallowwanaccess: true
lang: zh
