#!/bin/bash
# ACME证书管理脚本，支持Let's Encrypt证书申请、续订、查看和删除等功能
# Generated by github.com/halibotee

SCRIPT_VERSION="1.0.1"

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export LANG=en_US.UTF-8

# =============================================================================
# 1. 颜色输出函数
# =============================================================================
red(){ echo -e "\033[0;31m$1\033[0m"; }
green(){ echo -e "\033[0;32m$1\033[0m"; }
yellow(){ echo -e "\033[0;33m$1\033[0m"; }
cyan(){ echo -e "\033[0;36m$1\033[0m"; }
bold(){ echo -e "\033[1m$1\033[0m"; }
dim(){ echo -e "\033[2m$1\033[0m"; }

# =============================================================================
# 2. 脚本配置
# =============================================================================
ACME_SH_INSTALL_DIR="/root/.acme.sh/acme.sh"
AX_CERT_DIR="/etc/ax-certs"
PUBLIC_IP_SERVICE_1="ip.sb"
PUBLIC_IP_SERVICE_2="ipinfo.io/ip"

# =============================================================================
# 3. 系统检查
# =============================================================================
[[ $EUID -ne 0 ]] && yellow "请以root模式运行脚本" && exit

# 检测操作系统
if [[ -f /etc/redhat-release ]]; then
    release="Centos"
elif cat /etc/issue | grep -q -E -i "debian"; then
    release="Debian"
elif cat /etc/issue | grep -q -E -i "ubuntu"; then
    release="Ubuntu"
elif cat /etc/issue | grep -q -E -i "centos|red hat|redhat"; then
    release="Centos"
elif cat /proc/version | grep -q -E -i "debian"; then
    release="Debian"
elif cat /proc/version | grep -q -E -i "ubuntu"; then
    release="Ubuntu"
elif cat /proc/version | grep -q -E -i "centos|red hat|redhat"; then
    release="Centos"
else 
    red "不支持当前的系统，请选择使用Ubuntu,Debian,Centos系统。" && exit
fi

# 设置包管理器
case "$release" in
    "Centos") yumapt='yum -y';;
    "Ubuntu"|"Debian") yumapt="apt-get -y";;
esac

# =============================================================================
# 4. 日志函数
# =============================================================================
log(){ echo -e "[$(date '+%H:%M:%S')] $(bold "$1")"; }

# =============================================================================
# 5. 核心函数 - 安装依赖
# =============================================================================
install_dependencies(){
    local packages_to_install=()
    
    # 检查并添加缺失的依赖包
    ! command -v curl &> /dev/null && packages_to_install+=("curl")
    ! command -v wget &> /dev/null && packages_to_install+=("wget")
    ! command -v openssl &> /dev/null && packages_to_install+=("openssl")
    ! command -v socat &> /dev/null && packages_to_install+=("socat")
    
    # ACME DNS 模式依赖 (dig 命令)
    if ! command -v dig &> /dev/null; then
        if command -v apt-get &> /dev/null; then
            packages_to_install+=("dnsutils")
        elif command -v yum &> /dev/null || command -v dnf &> /dev/null; then
            packages_to_install+=("bind-utils")
        fi
    fi

    # 执行安装
    if [ ${#packages_to_install[@]} -gt 0 ]; then
        log "更新软件包列表并安装核心依赖: ${packages_to_install[*]}..."
        (apt-get update && apt-get install -y "${packages_to_install[@]}") > /dev/null 2>&1 || \
        (yum install -y epel-release && yum install -y "${packages_to_install[@]}") > /dev/null 2>&1 || \
        (dnf install -y "${packages_to_install[@]}") > /dev/null 2>&1
        green "依赖安装完成。"
    else
        green "所有依赖已安装。"
    fi
}

# =============================================================================
# 6. 核心函数 - 安装 acme.sh 客户端
# =============================================================================
install_acme_sh_client() {
    if [ -f "$ACME_SH_INSTALL_DIR" ]; then
        green "acme.sh 客户端已安装。"
        return 0
    fi
    
    log "正在安装 acme.sh 证书客户端..."
    
    local Aemail
    read -p "请输入注册 ACME 所需的邮箱 (回车自动生成): " Aemail
    if [ -z "$Aemail" ]; then
        local auto_email=$(date +%s%N | md5sum | cut -c 1-8)
        Aemail="$auto_email@gmail.com"
        yellow "已为您自动生成邮箱: $Aemail"
    fi

    # 使用 get.acme.sh 官方安装
    curl https://get.acme.sh | sh -s email=$Aemail
    if [ ! -f "$ACME_SH_INSTALL_DIR" ]; then
        red "acme.sh 客户端安装失败！"
        return 1
    fi
    
    "$ACME_SH_INSTALL_DIR" --upgrade --auto-upgrade
    "$ACME_SH_INSTALL_DIR" --set-default-ca --server letsencrypt
    green "acme.sh 客户端安装完成。"
}

# =============================================================================
# 7. 核心函数 - 检查 80 端口并释放
# =============================================================================
release_80_port() {
    log "正在检查 80 端口占用..."
    local pid=$(lsof -t -i:80)
    if [ -n "$pid" ]; then
        yellow "警告: 80 端口被进程 $pid 占用。"
        read -p "是否尝试强行释放 80 端口? [Y/n] (默认"Y"): " kill_confirm
        kill_confirm=${kill_confirm:-y}
        if [[ "$kill_confirm" == "y" || "$kill_confirm" == "Y" ]]; then
            log "正在强行释放 80 端口..."
            kill -9 $pid
            sleep 2
            if lsof -t -i:80 > /dev/null; then
                red "80 端口释放失败！"
                return 1
            else
                green "80 端口已释放。"
            fi
        else
            red "80 端口被占用，ACME Standalone 模式无法继续。"
            return 1
        fi
    fi
    return 0
}

# =============================================================================
# 8. 核心函数 - 获取或续订证书
# =============================================================================
ax_get_certificate() {
    local domain=$1
    local cert_dir="$AX_CERT_DIR/$domain"
    
    # 1. 检查证书是否已存在且有效
    if [ -f "$cert_dir/fullchain.cer" ]; then
        log "证书 $domain 已存在于 $cert_dir"
        
        # 检查证书有效期
        if command -v openssl &> /dev/null; then
            local expiry_date_str=$(openssl x509 -in "$cert_dir/fullchain.cer" -noout -enddate 2>/dev/null | cut -d= -f2)
            if [ -n "$expiry_date_str" ]; then
                local expiry_epoch=$(date -d "$expiry_date_str" +%s 2>/dev/null)
                local now_epoch=$(date +%s)
                if [ -n "$expiry_epoch" ]; then
                    local days_remaining=$(((expiry_epoch - now_epoch) / 86400))
                    if [ $days_remaining -lt 30 ]; then
                        yellow "证书即将过期（剩余 ${days_remaining} 天），建议续订。"
                        read -p "是否现在续订证书? [y/N]: " renew_confirm
                        if [[ "$renew_confirm" != "y" && "$renew_confirm" != "Y" ]]; then
                            return 0
                        fi
                    else
                        green "证书有效期充足（剩余 ${days_remaining} 天）。"
                        return 0
                    fi
                fi
            fi
        fi
    fi
    
    # 2. 确保 acme.sh 客户端已安装
    install_acme_sh_client || return 1
    
    # 3. 检查 DNS 解析 (确保域名解析到本机)
    log "正在验证 $domain 的 DNS 解析..."
    local v4=$(curl -s4m2 $PUBLIC_IP_SERVICE_1 || curl -s4m2 $PUBLIC_IP_SERVICE_2)
    local v6=$(curl -s6m2 $PUBLIC_IP_SERVICE_1 || curl -s6m2 $PUBLIC_IP_SERVICE_2)
    local domainIP=$(dig @8.8.8.8 +time=2 +short "$domain" 2>/dev/null | grep -m1 '^[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+$')
    
    if [[ -z "$domainIP" && -n "$v6" ]]; then
        domainIP=$(dig @2001:4860:4860::8888 +time=2 aaaa +short "$domain" 2>/dev/null | grep -m1 ':')
    fi
    
    if [[ -z "$domainIP" ]]; then
        red "错误: 无法解析 $domain 的 IP 地址。"
        return 1
    fi
    
    if [[ "$domainIP" != "$v4" && "$domainIP" != "$v6" ]]; then
        red "错误: $domain 解析的 IP ($domainIP) 与本机 IP ($v4 / $v6) 不匹配！"
        yellow "请确保 DNS 记录已正确设置，且 CDN (小黄云) 已关闭。"
        return 1
    fi
    green "DNS 验证通过: $domain -> $domainIP"

    # 4. 选择 ACME 模式
    read -p "选择 ACME 验证模式: [1] 80 端口 (Standalone) [2] DNS API (推荐): " acme_mode
    local issue_cmd=""

    if [ "$acme_mode" == "1" ]; then
        # 80 端口模式
        release_80_port || return 1
        local listen_opt=""
        if [[ "$domainIP" == "$v6" ]]; then
            listen_opt="--listen-v6"
        fi
        issue_cmd="$ACME_SH_INSTALL_DIR --issue -d $domain --standalone -k ec-256 $listen_opt --force --log"
    
    elif [ "$acme_mode" == "2" ]; then
        # DNS API 模式
        read -p "选择 DNS 服务商: [1] Cloudflare [2] DNSPod [3] Aliyun: " dns_provider
        local dns_api_cmd=""
        yellow "警告: API 密钥将保存在 acme.sh 配置中 (~/.acme.sh/account.conf)"
        
        case $dns_provider in
            1) # Cloudflare
                read -s -p "请输入 Cloudflare Global API Key: " GAK; echo
                export CF_Key="$GAK"
                read -p "请输入 Cloudflare 注册邮箱: " CFemail
                export CF_Email="$CFemail"
                dns_api_cmd="--dns dns_cf"
                ;;
            2) # DNSPod
                read -s -p "请输入 DNSPod DP_Id: " DPID; echo
                export DP_Id="$DPID"
                read -s -p "请输入 DNSPod DP_Key: " DPKEY; echo
                export DP_Key="$DPKEY"
                dns_api_cmd="--dns dns_dp"
                ;;
            3) # Aliyun
                read -s -p "请输入 Aliyun Ali_Key: " ALKEY; echo
                export Ali_Key="$ALKEY"
                read -s -p "请输入 Aliyun Ali_Secret: " ALSER; echo
                export Ali_Secret="$ALSER"
                dns_api_cmd="--dns dns_ali"
                ;;
            *)
                red "无效的服务商选择。"
                return 1
                ;;
        esac
        issue_cmd="$ACME_SH_INSTALL_DIR --issue -d $domain $dns_api_cmd -k ec-256 --force --log"
    
    else
        red "无效的模式选择。"
        return 1
    fi

    # 5. 执行申请
    log "正在执行 ACME 证书申请，请稍候..."
    eval $issue_cmd
    if [ $? -ne 0 ]; then
        red "ACME 证书申请失败！"
        yellow "请检查日志文件: /root/.acme.sh/acme.sh.log"
        return 1
    fi
    
    # 6. 安装证书到 ax 目录
    log "正在安装证书到 $cert_dir ..."
    mkdir -p "$cert_dir"
    "$ACME_SH_INSTALL_DIR" --install-cert -d "$domain" --ecc \
        --fullchain-file "$cert_dir/fullchain.cer" \
        --key-file "$cert_dir/private.key"
        
    if [ -f "$cert_dir/fullchain.cer" ]; then
        green "证书 $domain 已成功安装到 $cert_dir"
        # 确保 cron 任务已设置
        "$ACME_SH_INSTALL_DIR" --cron -f > /dev/null 2>&1
        return 0
    else
        red "证书安装失败！"
        return 1
    fi
}

# =============================================================================
# 9. 核心函数 - 查看证书列表
# =============================================================================
show_certificates_content() {
    # 检查 ACME 证书目录
    if [ ! -d "$AX_CERT_DIR" ] || [ -z "$(ls -A $AX_CERT_DIR 2>/dev/null)" ]; then
        yellow "未找到任何 ACME 证书。"
        echo
        return
    fi
    
    # 遍历 $AX_CERT_DIR 下的每个域名目录
    for domain_dir in "$AX_CERT_DIR"/*; do
        if [ -d "$domain_dir" ]; then
            local domain=$(basename "$domain_dir")
            local cert_file="$domain_dir/fullchain.cer"
            local key_file="$domain_dir/private.key"
            
            if [ -f "$cert_file" ] && [ -f "$key_file" ]; then
                local expiry_date_str=""
                local days_remaining="N/A"
                local status_color="green"
                
                # 尝试获取到期天数
                if command -v openssl &> /dev/null; then
                    expiry_date_str=$(openssl x509 -in "$cert_file" -noout -enddate 2>/dev/null | cut -d= -f2)
                    if [ -n "$expiry_date_str" ]; then
                        local expiry_epoch=$(date -d "$expiry_date_str" +%s 2>/dev/null)
                        local now_epoch=$(date +%s)
                        if [ -n "$expiry_epoch" ]; then
                            days_remaining=$(((expiry_epoch - now_epoch) / 86400))
                            
                            # 根据剩余天数设置颜色
                            if [ $days_remaining -lt 7 ]; then
                                status_color="red"
                            elif [ $days_remaining -lt 30 ]; then
                                status_color="yellow"
                            fi
                        fi
                    fi
                fi
                
                case $status_color in
                    "red") red "[域名] $domain (剩余 ${days_remaining} 天)" ;;
                    "yellow") yellow "[域名] $domain (剩余 ${days_remaining} 天)" ;;
                    *) green "[域名] $domain (剩余 ${days_remaining} 天)" ;;
                esac
                
                echo "  证书路径: $cert_file"
                echo "  密钥路径: $key_file"
                if [ -n "$expiry_date_str" ]; then
                    echo "  到期时间: $expiry_date_str"
                fi
                echo
            fi
        fi
    done
}

list_certificates() {
    clear
    echo "============================================================"
    echo "              ACME 证书列表"
    echo "============================================================"
    echo
    show_certificates_content
}

# =============================================================================
# 10. 核心函数 - 续订证书
# =============================================================================
renew_certificate() {
    read -p "请输入要续订的域名: " domain
    if [ -z "$domain" ]; then
        red "域名不能为空！"
        return 1
    fi
    
    local cert_dir="$AX_CERT_DIR/$domain"
    if [ ! -d "$cert_dir" ] || [ ! -f "$cert_dir/fullchain.cer" ]; then
        red "错误: 未找到域名 $domain 的证书！"
        return 1
    fi
    
    log "正在续订证书 $domain ..."
    "$ACME_SH_INSTALL_DIR" --renew -d "$domain" --ecc --force --log
    
    if [ $? -eq 0 ]; then
        green "证书 $domain 续订成功！"
        # 重新安装证书到 ax 目录
        "$ACME_SH_INSTALL_DIR" --install-cert -d "$domain" --ecc \
            --fullchain-file "$cert_dir/fullchain.cer" \
            --key-file "$cert_dir/private.key"
    else
        red "证书 $domain 续订失败！"
        return 1
    fi
}

# =============================================================================
# 11. 核心函数 - 删除证书
# =============================================================================
remove_certificate() {
    read -p "请输入要删除的域名: " domain
    if [ -z "$domain" ]; then
        red "域名不能为空！"
        return 1
    fi
    
    local cert_dir="$AX_CERT_DIR/$domain"
    if [ ! -d "$cert_dir" ]; then
        red "错误: 未找到域名 $domain 的证书！"
        return 1
    fi
    
    read -p "确认要删除域名 $domain 的证书吗? [y/N]: " confirm
    if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
        yellow "操作已取消。"
        return 0
    fi
    
    log "正在删除证书 $domain ..."
    
    # 从 acme.sh 中移除
    if [ -f "$ACME_SH_INSTALL_DIR" ]; then
        "$ACME_SH_INSTALL_DIR" --remove -d "$domain" --ecc > /dev/null 2>&1 || true
    fi
    
    # 删除本地证书目录
    rm -rf "$cert_dir"
    green "证书 $domain 已成功删除。"
}

# =============================================================================
# 12. 核心函数 - 卸载 acme.sh
# =============================================================================
uninstall_acme() {
    local silent=${1:-false}
    
    if [[ "$silent" != "true" ]]; then
        read -p "确认要卸载 ax-acme.sh 客户端吗？(证书将保留) [y/N]: " confirm
        if [[ "$confirm" != "y" && "$confirm" != "Y" ]]; then
            yellow "操作已取消。"
            return 0
        fi
    fi
    
    if [ ! -d "/root/.acme.sh" ]; then
        yellow "acme.sh 客户端未安装。"
        return 0
    fi
    
    log "正在卸载 acme.sh 客户端..."
    
    # 使用 acme.sh 的官方卸载命令
    if [ -f "/root/.acme.sh/acme.sh" ]; then
        /root/.acme.sh/acme.sh --uninstall > /dev/null 2>&1 || true
    fi
    
    # 删除整个 acme.sh 目录
    rm -rf /root/.acme.sh
    
    green "acme.sh 客户端已卸载，证书文件已保留在 $AX_CERT_DIR。"
}

# =============================================================================
# 13. 主菜单
# =============================================================================
main_menu() {
    while true; do
        clear
        green "============================================================"
        cyan "       ACME 证书管理脚本 v${SCRIPT_VERSION}"
        green "============================================================"
        echo
        
        # 显示 acme.sh 客户端状态
        if [ -f "$ACME_SH_INSTALL_DIR" ]; then
            local acme_version=$("$ACME_SH_INSTALL_DIR" --version 2>/dev/null | head -n1)
            green " 客户端状态: 已安装 ($acme_version)"
        else
            yellow " 客户端状态: 未安装"
        fi
        
        # 统计证书数量
        local cert_count=0
        if [ -d "$AX_CERT_DIR" ]; then
            cert_count=$(find "$AX_CERT_DIR" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)
        fi
        green " 已安装证书: ${cert_count} 个"
        green " 证书目录: $AX_CERT_DIR"
        
        # ACME 证书列表
        show_certificates_content

        echo
        cyan "------------------------------------------------------------"
        echo
        
        green " 1. 申请新证书"
        green " 2. 查看证书列表"
        green " 3. 续订证书"
        green " 4. 删除证书"
        echo
        red    " 5. 卸载"
        echo
        green " 0. 退出脚本"
        echo
        
        read -p " 请输入数字 [0-5]: " choice
        
        case "$choice" in
            1)
                read -p "请输入域名: " domain
                if [ -n "$domain" ]; then
                    ax_get_certificate "$domain"
                else
                    red "域名不能为空！"
                fi
                read -p $'\n按任意键返回...' -n1 -s
                ;;
            2)
                list_certificates
                read -p $'\n按任意键返回...' -n1 -s
                ;;
            3)
                renew_certificate
                read -p $'\n按任意键返回...' -n1 -s
                ;;
            4)
                remove_certificate
                read -p $'\n按任意键返回...' -n1 -s
                ;;
            5)
                uninstall_acme
                read -p $'\n按任意键返回...' -n1 -s
                ;;
            0)
                exit 0
                ;;
            *)
                red "输入错误，请重新输入。"
                sleep 1
                ;;
        esac
    done
}

# =============================================================================
# 14. 脚本入口
# =============================================================================

# 处理命令行参数
if [[ "$1" == "-u" ]]; then
    uninstall_acme true
    exit 0
fi

if [[ "$1" == "-n" ]]; then
    install_dependencies
    install_acme_sh_client

    domain="$2"
    if [ -z "$domain" ]; then
        read -p "请输入域名: " domain
    fi
    
    if [ -n "$domain" ]; then
        ax_get_certificate "$domain"
    else
        red "域名不能为空！"
        exit 1
    fi
    exit 0
fi


install_dependencies
install_acme_sh_client

# 显示主菜单
main_menu
