#!/bin/bash
# VPS优化脚本，包含网络参数调优、BBR加速、ZRAM内存压缩等功能 
# Generated by github.com/halibotee

SCRIPT_VERSION="1.1.0"

red() { printf '\033[31m%s\033[0m\n' "$*"; }
green() { printf '\033[32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[33m%s\033[0m\n' "$*"; }
blue() { printf '\033[34m%s\033[0m\n' "$*"; }

set -euo pipefail
IFS=$'\n\t'

export FORCE_YES=0
if [ "${1:-}" = "-y" ] || [ "${1:-}" = "--yes" ]; then
    FORCE_YES=1
fi


BACKUP_DIR="/etc/vps_optimizert_backup"
LOG_FILE="/var/log/vps_optimizert.log"
ACTION_LOG="${BACKUP_DIR}/actions.log"
export DEBIAN_FRONTEND=noninteractive

declare -ga PKG_CMD_INSTALL
declare -ga PKG_CMD_REMOVE
declare -ga PKG_CMD_CHECK
declare -ga PKG_CMD_UPDATE

FN_TRIM_SERVICES_LIST=(
"ModemManager.service"
"rpcbind.service"
"unattended-upgrades.service"
"bluetooth.service"
)

FN_NETWORK_SERVICES_LIST=(
"xray"
"hysteria2"
"hysteria"
"udp2raw"
"kcptun"
"ax-xray@*"
"ax-hysteria2@*"
"ax-udp2raw@*"
"ax-kcptun@*"
"xray@*"
"hysteria2@*"
"udp2raw@*"
"kcptun@*"
)

mkdir -p "$BACKUP_DIR"
touch "$LOG_FILE"
>> "$LOG_FILE"
touch "$ACTION_LOG"

fn_log() {
    if [ -z "${LOG_Y_RECORDED:-}" ]; then
        if [ $FORCE_YES -eq 1 ]; then
            local ts=$(date '+%F %T')
            printf '%s [%s] %s\n' "$ts" "警告" "非交互模式 (-y) 已激活。将自动同意所有提示。" >> "$LOG_FILE"
        fi
        export LOG_Y_RECORDED=1
    fi
    
local level="$1"; shift
local msg="$*"
local ts
ts=$(date '+%F %T')
printf '%s [%s] %s\n' "$ts" "$level" "$msg" >> "$LOG_FILE"
}

fn_log_action() {
    local action="$1"
    local value="$2"
    echo "${action}:${value}" >> "$ACTION_LOG"
    fn_log "调试" "记录操作: ${action}:${value}"
}

fn_check_if_optimized() {
    if [ ! -f "$ACTION_LOG" ]; then
        return 1
    fi
    
    local action_count
    action_count=$(grep -vc -E '(^#|^$)' "$ACTION_LOG" 2>/dev/null || true)
    
    if [ "${action_count:-0}" -gt 0 ]; then
        return 0
    else
        return 1
    fi
}

fn_check_root() {
if [ "$EUID" -ne 0 ]; then
echo "错误: 本脚本必须以 root 权限运行。"
fn_log "错误" "本脚本必须以 root 权限运行。"
exit 1
fi
}

fn_check_pkg_lock() {
    if [ "$OS_ID" = "debian" ] || [ "$OS_ID" = "ubuntu" ]; then
        if fuser /var/lib/dpkg/lock-frontend > /dev/null 2>&1 || fuser /var/lib/dpkg/lock > /dev/null 2>&1; then
            fn_log "警告" "检测到 APT/DPKG 锁。"
            return 1
        fi
    elif [ "$OS_ID" = "fedora" ] || [ "$OS_ID" = "rhel" ] || [ "$OS_ID" = "centos" ] || [ "$OS_ID" = "almalinux" ] || [ "$OS_ID" = "rocky" ]; then
        if [ -f /var/cache/dnf/metadata_lock.pid ] && pgrep -F /var/cache/dnf/metadata_lock.pid > /dev/null 2>&1; then
            fn_log "警告" "检测到 DNF 锁。"
            return 1
        fi
    fi
    return 0
}

fn_wait_for_pkg_lock() {
    local max_wait=120
    local count=0
    fn_log "信息" "检查包管理器锁..."
    while ! fn_check_pkg_lock; do
        if [ "$count" -ge "$max_wait" ]; then
            fn_log "错误" "等待包管理器锁超时 (120 秒)。操作可能失败。"
            return 1
        fi
        fn_log "警告" "检测到包管理器锁，等待 5 秒... ($count/$max_wait)"
        sleep 5
        count=$((count + 5))
    done
    fn_log "信息" "包管理器锁已释放。"
    return 0
}

fn_detect_os() {
    
    if [ -f /etc/os-release ]; then
        source /etc/os-release
        OS_PRETTY="${PRETTY_NAME:-unknown}"
        OS_ID="${ID:-unknown}"
        OS_VER="${VERSION_ID:-unknown}"
        echo "检测到操作系统: $OS_PRETTY"
        fn_log "信息" "检测到操作系统: $OS_PRETTY"
    else
        echo "错误: 无法检测到操作系统 (/etc/os-release 不存在)。"
        fn_log "错误" "无法检测到操作系统 (/etc/os-release 不存在)。"
        exit 1
    fi

    case "$OS_ID" in
        debian|ubuntu)
            PKG_CMD_INSTALL=("apt-get" "install" "-y")
            PKG_CMD_REMOVE=("apt-get" "remove" "-y" "--purge")
            PKG_CMD_CHECK=("dpkg" "-s")
            PKG_CMD_UPDATE=("apt-get" "update")
            ;;
        fedora|rhel|centos|almalinux|rocky)
            PKG_CMD_INSTALL=("dnf" "install" "-y")
            PKG_CMD_REMOVE=("dnf" "remove" "-y")
            PKG_CMD_CHECK=("rpm" "-q")
            PKG_CMD_UPDATE=("dnf" "check-update" "--quiet")
            ;;
        *)
            echo "错误: 不支持的操作系统 $OS_ID。"
            fn_log "错误" "不支持的操作系统 $OS_ID。"
            exit 1
            ;;
    esac

    MEM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}' || echo 0)
    MEM_MB=$(( MEM_KB / 1024 ))
    echo "物理内存: ${MEM_MB} MB"
    fn_log "信息" "物理内存: ${MEM_MB} MB"
    if ! command -v systemctl > /dev/null 2>&1; then
        echo "错误: 未找到 Systemd。本脚本需要 systemd。"
        fn_log "错误" "未找到 Systemd。本脚本需要 systemd。"
        exit 1
    fi
}

fn_backup_state() {
fn_log "信息" "正在创建备份于 $BACKUP_DIR ..."
mkdir -p "$BACKUP_DIR" || { fn_log "错误" "无法创建 $BACKUP_DIR"; return 1; }
cp -an /etc/fstab "${BACKUP_DIR}/fstab.bak" 2>/dev/null || true
cp -an /etc/systemd/resolved.conf "${BACKUP_DIR}/resolved.conf.bak" 2>/dev/null || true
cp -an /etc/systemd/system.conf "${BACKUP_DIR}/system.conf.bak" 2>/dev/null || true
cp -an /etc/sysctl.conf "${BACKUP_DIR}/sysctl.conf.bak" 2>/dev/null || true
cp -ran /etc/sysctl.d "${BACKUP_DIR}/sysctl.d.bak" 2>/dev/null || true
cp -ran /etc/systemd/journald.conf.d "${BACKUP_DIR}/journald.conf.d.bak" 2>/dev/null || true
[ -f /etc/selinux/config ] && cp -an /etc/selinux/config "${BACKUP_DIR}/selinux.config.bak" 2>/dev/null || true
sysctl -n net.ipv4.tcp_congestion_control > "${BACKUP_DIR}/sysctl_con_algo.bak" 2>/dev/null || true
sysctl -n net.core.default_qdisc > "${BACKUP_DIR}/sysctl_q_algo.bak" 2>/dev/null || true

systemctl list-unit-files --type=service --state=enabled | awk '/enabled/ {print $1}' > "${BACKUP_DIR}/enabled_services.before.txt" 2>/dev/null || true

echo "# vps_optimizert action log ($(date))" > "$ACTION_LOG"

fn_log "信息" "备份完成。"
return 0
}

fn_fix_apt_sources_if_needed() {
fn_wait_for_pkg_lock || { fn_log "错误" "包管理器锁等待失败"; return 1; }
fn_log "信息" "检查包管理器源健康状况..."

if [ "$OS_ID" = "debian" ] || [ "$OS_ID" = "ubuntu" ]; then
    mkdir -p /etc/apt/apt.conf.d
    cat > /etc/apt/apt.conf.d/99-force-ipv4 <<'EOF'
Acquire::ForceIPv4 "true";
EOF
    fn_log "调试" "已创建 /etc/apt/apt.conf.d/99-force-ipv4 (强制 APT 使用 IPv4)"
    fn_log_action "CREATE_FILE" "/etc/apt/apt.conf.d/99-force-ipv4"
fi

if "${PKG_CMD_UPDATE[@]}"; then
fn_log "成功" "包管理器源正常。"
return 0
else
fn_log "警告" "包管理器 update 失败。将尝试保守替换 sources.list (仅限 Debian/Ubuntu)"

if [ "$OS_ID" = "debian" ] || [ "$OS_ID" = "ubuntu" ]; then
    if command -v lsb_release > /dev/null 2>&1; then
        codename=$(lsb_release -cs)
    else
        codename=$(grep VERSION_CODENAME /etc/os-release 2>/dev/null | cut -d= -f2 || true)
    fi
    if [ -z "${codename:-}" ]; then
        fn_log "错误" "无法确定发行版代号，跳过自动替换源。"
        return 1
    fi
    cp -an /etc/apt/sources.list "${BACKUP_DIR}/apt.sources.list.bak" 2>/dev/null || true
    
    if [ "$OS_ID" = "debian" ]; then
cat > /etc/apt/sources.list <<EOF
deb http://deb.debian.org/debian/ $codename main contrib non-free non-free-firmware
deb http://deb.debian.org/debian/ $codename-updates main contrib non-free non-free-firmware
deb http://security.debian.org/debian-security/ $codename-security main contrib non-free non-free-firmware
EOF
    elif [ "$OS_ID" = "ubuntu" ]; then
cat > /etc/apt/sources.list <<EOF
deb http://archive.ubuntu.com/ubuntu/ $codename main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ $codename-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu/ $codename-security main restricted universe multiverse
EOF
    fi
else
    fn_log "错误" "此操作系统不支持自动替换源。"
    return 1
fi

if "${PKG_CMD_UPDATE[@]}"; then
    fn_log "成功" "APT 源替换并刷新成功。"
    return 0
else
    local update_cmd_str="${PKG_CMD_UPDATE[@]}"
    fn_log "错误" "替换源后 ${update_cmd_str} 仍然失败。"
    echo "-----------------------------------------------------"
    echo "[错误] 致命错误: 'apt update' 彻底失败。"
    echo "       请检查 DNS (例如 /etc/resolv.conf) 和网络连接。"
    echo "-----------------------------------------------------"
    return 1
fi
fi
}


fn_setup_journald_volatile() {
local journal_storage
journal_storage=$(systemd-analyze cat-config systemd/journald.conf | grep -i '^Storage=' | tail -n 1 | cut -d= -f2 2>/dev/null || echo "disk")
if [ "$journal_storage" == "volatile" ]; then
    fn_log "信息" "journald 已是 volatile 模式，跳过。"
    return 2
fi

fn_log "信息" "配置 journald 为 volatile (内存) 模式 (RuntimeMaxUse=16M)..."
mkdir -p /etc/systemd/journald.conf.d
local conf_file="/etc/systemd/journald.conf.d/10-volatile.conf"
cat > "$conf_file" <<'EOF'
[Journal]
Storage=volatile
RuntimeMaxUse=16M
MaxRetentionSec=1month
EOF
fn_log_action "CREATE_FILE" "$conf_file"
systemctl restart systemd-journald > /dev/null 2>&1 || true
fn_log "成功" "journald 已配置为 volatile 模式。"
return 0
}


# 内存分层检测: tiny (<=512MB) / small (512-1024MB) / medium (1024-2048MB) / large (>2048MB)
fn_detect_memory_tier() {
    if [ -n "${MEMORY_TIER:-}" ]; then
        return 0
    fi
    if [ "${MEM_MB:-0}" -le 512 ]; then
        MEMORY_TIER="tiny"
    elif [ "${MEM_MB:-0}" -le 1024 ]; then
        MEMORY_TIER="small"
    elif [ "${MEM_MB:-0}" -le 2048 ]; then
        MEMORY_TIER="medium"
    else
        MEMORY_TIER="large"
    fi
    fn_log "信息" "内存分层: $MEMORY_TIER (${MEM_MB}MB)"
    echo "内存分层: $MEMORY_TIER (${MEM_MB}MB)"
}

# 网络配置优化方案 (来自 tcp.sh 菜单27)
fn_setup_aggressive_network() {
    echo "[任务] 系统配置优化方案 - 交互式参数配置"
    echo "-----------------------------------------------------"

    fn_detect_memory_tier

    local pid_max file_max inotify_max conntrack_max min_free_kbytes
    case "$MEMORY_TIER" in
        tiny)
            pid_max=32768; file_max=131072; inotify_max=512; conntrack_max=32768; min_free_kbytes=32768
            ;;
        small)
            pid_max=32768; file_max=524288; inotify_max=1024; conntrack_max=65536; min_free_kbytes=65536
            ;;
        medium)
            pid_max=65535; file_max=1000000; inotify_max=4096; conntrack_max=131072; min_free_kbytes=131072
            ;;
        *)
            pid_max=65535; file_max=2000000; inotify_max=8192; conntrack_max=262144; min_free_kbytes=262144
            ;;
    esac

    # 加载/配置网络参数
    local net_conf="/etc/ax-optz.conf"
    local latency local_bw vps_bw vps_mem=$MEM_MB
    if [ -f "$net_conf" ]; then
        source "$net_conf"
        latency=${LATENCY:-$latency}
        local_bw=${LOCAL_BW:-$local_bw}
        vps_bw=${VPS_BW:-$vps_bw}
        echo "已读取配置文件: $net_conf"
    fi
    : ${latency:=180}; : ${local_bw:=500}; : ${vps_bw:=100}
    echo ""
    echo "--- 网络参数配置 (直接回车使用默认值) ---"
    read -rp "延迟 (ms) [${latency}]: " input
    [[ -n "$input" ]] && latency=$input
    read -rp "本地带宽 (Mbps) [${local_bw}]: " input
    [[ -n "$input" ]] && local_bw=$input
    read -rp "VPS带宽 (Mbps) [${vps_bw}]: " input
    [[ -n "$input" ]] && vps_bw=$input
    echo ""
    cat > "$net_conf" <<EOF
# Network parameters for ax-optz.sh
LATENCY=$latency
LOCAL_BW=$local_bw
VPS_BW=$vps_bw
EOF
    echo "网络参数: 延迟=${latency}ms, 本地带宽=${local_bw}Mbps, VPS带宽=${vps_bw}Mbps, 内存=${vps_mem}MB"
    fn_log "信息" "网络优化参数: 延迟=${latency}ms, 带宽=${local_bw}/${vps_bw}Mbps, 内存=${vps_mem}MB"
    
    # 计算优化参数
    local min_bw=$((local_bw < vps_bw ? local_bw : vps_bw))
    local bdp=$((min_bw * 1000000 * latency / 8 / 1000))
    
    local rmem_max=$((bdp * 2))
    local wmem_max=$((bdp * 3 / 2))
    local max_mem_bytes=$((vps_mem * 1024 * 1024 * 50 / 100))
    [[ $rmem_max -gt $max_mem_bytes ]] && rmem_max=$max_mem_bytes
    [[ $wmem_max -gt $max_mem_bytes ]] && wmem_max=$max_mem_bytes
    [[ $rmem_max -lt 1048576 ]] && rmem_max=1048576
    [[ $wmem_max -lt 1048576 ]] && wmem_max=1048576
    
    local netdev_max_backlog=$((min_bw * 10))
    [[ $netdev_max_backlog -gt 10000 ]] && netdev_max_backlog=10000
    [[ $netdev_max_backlog -lt 1000 ]] && netdev_max_backlog=1000
    
    local somaxconn=$((vps_mem * 20))
    [[ $somaxconn -gt 16384 ]] && somaxconn=16384
    [[ $somaxconn -lt 512 ]] && somaxconn=512
    
    local tcp_max_syn_backlog=$((somaxconn * 4))
    [[ $tcp_max_syn_backlog -gt 65536 ]] && tcp_max_syn_backlog=65536
    
    local tcp_init_cwnd=$((latency / 20 + 10))
    [[ $tcp_init_cwnd -gt 32 ]] && tcp_init_cwnd=32
    [[ $tcp_init_cwnd -lt 10 ]] && tcp_init_cwnd=10
    
    # 创建配置文件 /etc/sysctl.d/99-net.conf
    local config_file="/etc/sysctl.d/99-net.conf"
    fn_log "信息" "创建网络优化配置: $config_file (内存分层: ${MEMORY_TIER})"
    
    cat > "$config_file" <<EOF
# 网络优化配置 - Generated by ax-optz.sh v${SCRIPT_VERSION}
# 延迟: ${latency}ms, 本地带宽: ${local_bw}Mbps, VPS带宽: ${vps_bw}Mbps, 内存: ${vps_mem}MB, 内存分层: ${MEMORY_TIER}

# Kernel 参数
kernel.pid_max = ${pid_max}
kernel.panic = 1
kernel.sysrq = 1
kernel.core_pattern = core_%e
kernel.printk = 3 4 1 3
kernel.numa_balancing = 0
kernel.sched_autogroup_enabled = 0
kernel.timer_migration = 0

# 虚拟内存
vm.swappiness = 5
vm.dirty_ratio = 5
vm.dirty_background_ratio = 2
vm.panic_on_oom = 1
vm.overcommit_memory = 0
vm.min_free_kbytes = ${min_free_kbytes}
vm.vfs_cache_pressure = 50
vm.zone_reclaim_mode = 0

# 核心网络缓冲区
net.core.netdev_max_backlog = ${netdev_max_backlog}
net.core.rmem_max = ${rmem_max}
net.core.wmem_max = ${wmem_max}
net.core.rmem_default = 262144
net.core.wmem_default = 262144
net.core.somaxconn = ${somaxconn}
net.core.optmem_max = 262144
net.core.busy_poll = 0
net.core.busy_read = 0

# 连接跟踪 (内存分层)
net.netfilter.nf_conntrack_max = ${conntrack_max}
net.nf_conntrack_max = ${conntrack_max}

# TCP 优化
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_timestamps = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_max_tw_buckets = 32768
net.ipv4.tcp_sack = 1
net.ipv4.tcp_fack = 1
net.ipv4.tcp_rmem = 32768 262144 ${rmem_max}
net.ipv4.tcp_wmem = 32768 262144 ${wmem_max}
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_notsent_lowat = 16384
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_adv_win_scale = 2
net.ipv4.tcp_moderate_rcvbuf = 1
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.tcp_init_cwnd = ${tcp_init_cwnd}
net.ipv4.tcp_max_syn_backlog = ${tcp_max_syn_backlog}
net.ipv4.tcp_max_orphans = 32768
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_syn_retries = 2
net.ipv4.tcp_abort_on_overflow = 0
net.ipv4.tcp_stdurg = 0
net.ipv4.tcp_rfc1337 = 0
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 6
net.ipv4.tcp_ecn = 0
net.ipv4.tcp_ecn_fallback = 0
net.ipv4.tcp_frto = 0

# BBR pacing (BBR v2+) - 提高高带宽代理吞吐量
net.ipv4.tcp_pacing_ss_ratio = 200
net.ipv4.tcp_pacing_ca_ratio = 120

# UDP 优化 (适用于 hysteria2 / udp2raw)
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192
net.ipv4.udp_mem = 102400 873800 16777216
net.ipv4.udp_early_demux = 1

# IP 配置
net.ipv4.ip_forward = 1
net.ipv4.ip_local_port_range = 1024 65535
net.ipv4.ip_no_pmtu_disc = 0
net.ipv4.route.gc_timeout = 100

# Neighbor 配置
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.neigh.default.gc_thresh3 = 4096
net.ipv4.neigh.default.gc_thresh2 = 2048
net.ipv4.neigh.default.gc_thresh1 = 512

# ICMP
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.icmp_ignore_bogus_error_responses = 1

# 安全配置
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.arp_announce = 2
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.default.arp_ignore = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.route_localnet = 1

# 文件系统 (内存分层)
fs.file-max = ${file_max}
fs.inotify.max_user_instances = ${inotify_max}
fs.nr_open = ${file_max}

# BBR+FQ
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr

# IPv6 禁用
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 0
EOF

    # 加载 BBR 模块
    modprobe tcp_bbr 2>/dev/null || modprobe tcp_bbr2 2>/dev/null || modprobe tcp_bbr3 2>/dev/null || fn_log "警告" "无法加载 BBR 模块"
    
    fn_log_action "CREATE_FILE" "$config_file"
    fn_log "成功" "网络优化配置文件已创建: $config_file (分层=${MEMORY_TIER})"
    
    return 0
}

_fn_cleanup_fallback_swap() {
    local fallback_swap="/swapfile_zram"
    
    if [ ! -f "$fallback_swap" ]; then
        return 0
    fi

    if swapon -s | grep -q "$fallback_swap"; then
        fn_log "信息" "ZRAM 已激活，正在自动清理不再需要的回退 swapfile..."
        (swapoff "$fallback_swap") >> "$LOG_FILE" 2>&1 || true
        (rm -f "$fallback_swap") >> "$LOG_FILE" 2>&1 || true
        fn_log "成功" "已自动清理回退 swapfile: $fallback_swap"
    
    elif [ -f "$fallback_swap" ]; then
         fn_log "调试" "检测到未激活的回退 swapfile，正在清理..."
         (rm -f "$fallback_swap") >> "$LOG_FILE" 2>&1 || true
    fi
    return 0
}

fn_setup_zram_adaptive() {
    fn_log "信息" "启用 ZRAM (切换到 zram-tools 方案)..."

    if systemctl is-active zramswap.service >/dev/null 2>&1; then
        fn_log "信息" "ZRAM (zram-tools) 已激活，跳过。"
        _fn_cleanup_fallback_swap
        return 2
    fi
    
    if "${PKG_CMD_CHECK[@]}" systemd-zram-generator >/dev/null 2>&1; then
        fn_log "信息" "检测到冲突的 systemd-zram-generator，正在卸载..."
        fn_wait_for_pkg_lock || { fn_log "错误" "包管理器锁等待失败"; return 1; }
        "${PKG_CMD_REMOVE[@]}" systemd-zram-generator >>"$LOG_FILE" 2>&1 || true
        fn_log_action "UNINSTALL_PKG" "systemd-zram-generator"
    fi
    
    if "${PKG_CMD_CHECK[@]}" zram-tools >/dev/null 2>&1; then
        fn_log "信息" "ZRAM (zram-tools) 已安装。"
    else
        fn_log "信息" "正在安装 ZRAM (zram-tools)..."
        fn_wait_for_pkg_lock || { fn_log "错误" "包管理器锁等待失败"; return 1; }
        "${PKG_CMD_INSTALL[@]}" zram-tools >>"$LOG_FILE" 2>&1 || { 
            fn_log "警告" "zram-tools 安装失败"; 
            fn_setup_zram_fallback "zram-tools 安装失败"; 
            return 1; 
        }
        fn_log_action "INSTALL_PKG" "zram-tools"
        fn_log "信息" "ZRAM (zram-tools) 安装完成。"
    fi

    mem_mb="$MEM_MB"
    local zram_percent=100
    fn_log "信息" "ZRAM 目标大小: ${zram_percent}% 物理内存 (高风险设置)"

    local old_conf_file="/etc/systemd/zram-generator.conf"
    if [ -f "$old_conf_file" ]; then
        rm -f "$old_conf_file"
        fn_log "调试" "已移除旧的 zram-generator.conf"
    fi

    local conf_file="/etc/default/zramswap"
    cat > "$conf_file" <<EOF
# Configuration for zram-tools
ALGO=lz4
PERCENT=${zram_percent}
PRIORITY=100
EOF
    fn_log_action "CREATE_FILE" "$conf_file"
    fn_log "调试" "已写入 $conf_file"

    modprobe zram || true
    fn_log "调试" "已执行 modprobe zram"
    
    (systemctl restart zramswap.service) >> "$LOG_FILE" 2>&1 || true
    fn_log "调试" "已重启 zramswap.service (尝试 1)，等待 3 秒..."
    sleep 3

    if [ -b /dev/zram0 ] && swapon -s | grep -q 'zram'; then
        fn_log "成功" "ZRAM (zram-tools) 已激活 (尝试 1 成功)"
        (swapon -s) >> "$LOG_FILE" 2>&1
        systemctl enable zramswap.service >/dev/null 2>&1 || true
        _fn_cleanup_fallback_swap
        return 0
    fi

    fn_log "警告" "ZRAM 激活失败 (尝试 1)，将尝试清理内核缓存后重试..."
    (sync && echo 3 > /proc/sys/vm/drop_caches) 2>/dev/null || true
    fn_log "调试" "已清理内核缓存，等待 2 秒..."
    sleep 2

    (systemctl restart zramswap.service) >> "$LOG_FILE" 2>&1 || true
    fn_log "调试" "已重启 zramswap.service (尝试 2)，等待 3 秒..."
    sleep 3

    if [ -b /dev/zram0 ] && swapon -s | grep -q 'zram'; then
        fn_log "成功" "ZRAM (zram-tools) 已激活 (尝试 2 成功)"
        (swapon -s) >> "$LOG_FILE" 2>&1
        systemctl enable zramswap.service >/dev/null 2>&1 || true
        _fn_cleanup_fallback_swap
        return 0
    else
        fn_log "错误" "ZRAM (zram-tools) 激活失败 (尝试 2 仍失败)，使用 swapfile 回退"
        fn_log "警告" "100% 内存分配失败。这在低内存 VPS 上是常见情况 (os error 12)。"
        fn_setup_zram_fallback "ZRAM 激活失败"
        return 1
    fi
}

fn_setup_zram_fallback() {
    local reason="$1"
    fn_log "警告" "$reason, 使用 swapfile 回退"

    local swapfile="/swapfile_zram"
    local swapsize_mb=$(( MEM_MB < 512 ? MEM_MB : 512 ))
    
    if [ -f "$swapfile" ]; then
        fn_log "调试" "检测到旧的 swapfile，正在移除..."
        swapoff "$swapfile" 2>/dev/null || true
        rm -f "$swapfile" 2>/dev/null || true
    fi

    fn_log "调试" "创建 swapfile: $swapfile (大小: ${swapsize_mb}M)"
    (fallocate -l "${swapsize_mb}M" "$swapfile" || dd if=/dev/zero of="$swapfile" bs=1M count="$swapsize_mb") >> "$LOG_FILE" 2>&1
    fn_log_action "CREATE_FILE" "$swapfile"
    
    chmod 600 "$swapfile"
    (mkswap "$swapfile") >> "$LOG_FILE" 2>&1 || true
    fn_log "调试" "mkswap $swapfile"
    
    (swapon "$swapfile") >> "$LOG_FILE" 2>&1 || true
    fn_log "调试" "swapon $swapfile"
    
    if swapon -s | grep -q "$(basename "$swapfile")"; then
        fn_log "成功" "Swapfile 回退启用 (${swapsize_mb} MB)"
        (swapon -s) >> "$LOG_FILE" 2>&1
    else
        fn_log "错误" "Swapfile 回退启用失败。"
    fi
}

fn_trim_services_auto() {
    local changes_made=0
    fn_log "信息" "正在精简系统服务..."

    for svc in "${FN_TRIM_SERVICES_LIST[@]}"; do
        if systemctl is-enabled "$svc" >/dev/null 2>&1; then
            fn_log "信息" "正在屏蔽服务: $svc"
            systemctl mask "$svc" >/dev/null 2>&1 || true
            systemctl stop "$svc" >/dev/null 2>&1 || true
            fn_log_action "MASK_SERVICE" "$svc"
            changes_made=1
        fi
    done

    local idle_timers=(
        "systemd-tmpfiles-clean.timer"
        "apt-daily.timer"
        "apt-daily-upgrade.timer"
        "dpkg-db-backup.timer"
        "fstrim.timer"
        "motd-news.timer"
    )
    for tmr in "${idle_timers[@]}"; do
        if systemctl is-enabled "$tmr" >/dev/null 2>&1; then
            systemctl mask "$tmr" >/dev/null 2>&1 || true
            systemctl stop "$tmr" >/dev/null 2>&1 || true
            fn_log_action "MASK_SERVICE" "$tmr"
            changes_made=1
        fi
    done

    local extra_conf="/etc/sysctl.d/99-vps-extra.conf"
    if [[ ! -f "$extra_conf" ]]; then
        cat > "$extra_conf" <<'EOF'
net.ipv4.tcp_slow_start_after_idle = 0
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_rfc1337 = 1
EOF
        sysctl -p "$extra_conf" >/dev/null 2>&1 || true
        fn_log_action "CREATE_FILE" "$extra_conf"
    fi

    if [ "$changes_made" -eq 0 ]; then
        fn_log "信息" "所有目标服务均已屏蔽，无需操作。"
        return 2
    fi

    fn_log "成功" "系统服务精简完成。"
    return 0
}

fn_prioritize_network_services_auto() {
local changes_made=0

local services_list_str
local IFS=','
services_list_str="${FN_NETWORK_SERVICES_LIST[*]}"
fn_log "信息" "正在搜索匹配的网络代理服务 (${services_list_str})..."

local found_names=()
for pattern in "${FN_NETWORK_SERVICES_LIST[@]}"; do
    while read -r service_file; do
        [ -z "$service_file" ] && continue
        
        local base_name="${service_file%.service}" 
        found_names+=("$base_name")
        
    done < <(systemctl list-unit-files --type=service --no-legend "${pattern}.service" 2>/dev/null | awk '{print $1}')
done

local detected_svcs=()
mapfile -t detected_svcs < <(printf "%s\n" "${found_names[@]}" | sort -u)


if [ ${#detected_svcs[@]} -eq 0 ]; then
fn_log "信息" "未检测到网络代理服务，无需优化。"
return 2
fi

local detected_svcs_str
IFS=','
detected_svcs_str="${detected_svcs[*]}"
fn_log "信息" "检测到: ${detected_svcs_str}。开始应用服务优化..."

for svc in "${detected_svcs[@]}"; do
    local conf_file="/etc/systemd/system/${svc}.service.d/90-vps_optimizert.conf"
    if [ -f "$conf_file" ]; then
        fn_log "调试" "配置文件 $conf_file 已存在，跳过 $svc。"
        continue
    fi
    
    fn_log "调试" "为 $svc 设置 RealTime 调度, Nice=-19, Limits."
    
    local svc_conf_dir="/etc/systemd/system/${svc}.service.d"
    mkdir -p "$svc_conf_dir"
    cat > "$conf_file" <<EOF
[Service]
# Extreme Performance Tuning
Nice=-19
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=20
LimitNOFILE=1000000
LimitNPROC=1000000
EOF
    fn_log_action "CREATE_FILE" "$conf_file"
    changes_made=1
done

if [ "$changes_made" -eq 0 ]; then
     fn_log "信息" "网络代理服务均已配置，无需刷新。"
     return 2
fi

if [ "$changes_made" -eq 1 ]; then
    fn_log "调试" "重载 systemd daemon..."
    (systemctl daemon-reload) >> "$LOG_FILE" 2>&1
fi
fn_log "成功" "网络服务优化成功 (${detected_svcs_str})。"
return 0
}

fn_set_system_limits() {
    fn_log "信息" "设置系统级资源限制 (limits.conf)..."
    local limits_file="/etc/security/limits.conf"
    
    if grep -q "vps_optimizert" "$limits_file"; then
        fn_log "信息" "limits.conf 已包含优化配置，跳过。"
        return 2
    fi
    
    cp "$limits_file" "${limits_file}.bak" 2>/dev/null || true
    
    cat >> "$limits_file" <<'EOF'

# Added by vps_optimizert
* soft nofile 1000000
* hard nofile 1000000
* soft nproc 1000000
* hard nproc 1000000
root soft nofile 1000000
root hard nofile 1000000
root soft nproc 1000000
root hard nproc 1000000
EOF
    fn_log_action "MODIFY_FILE" "$limits_file"
    fn_log "成功" "已更新 /etc/security/limits.conf"
    return 0
}

fn_setup_earlyoom() {
    fn_log "信息" "配置 earlyoom (OOM 保护)..."

    if systemctl is-active earlyoom >/dev/null 2>&1; then
        fn_log "信息" "earlyoom 已激活，跳过。"
        return 2
    fi

    if ! "${PKG_CMD_CHECK[@]}" earlyoom >/dev/null 2>&1; then
        fn_log "信息" "正在安装 earlyoom..."
        fn_wait_for_pkg_lock || { fn_log "错误" "包管理器锁等待失败"; return 1; }
        "${PKG_CMD_INSTALL[@]}" earlyoom >>"$LOG_FILE" 2>&1 || {
            fn_log "警告" "earlyoom 安装失败";
            return 1;
        }
        fn_log_action "INSTALL_PKG" "earlyoom"
    fi

    mkdir -p /etc/default
    cat > /etc/default/earlyoom <<'EOF'
EARLYOOM_ARGS="-m 5 -s 10 -r 60 --avoid '^(X|chrome|firefox)$'"
EOF
    fn_log_action "CREATE_FILE" "/etc/default/earlyoom"

    systemctl enable --now earlyoom >/dev/null 2>&1 || true

    if systemctl is-active earlyoom >/dev/null 2>&1; then
        fn_log "成功" "earlyoom 已激活。"
        return 0
    else
        fn_log "错误" "earlyoom 启动失败。"
        return 1
    fi
}

fn_optimize_auto() {
    local result

    if fn_check_if_optimized; then
        echo "检测到系统已被优化过，正在重新执行优化..."
        fn_log "信息" "系统已被优化过，用户选择重新优化。"
    fi

    fn_backup_state || { echo "[失败] 备份失败，退出。"; return 1; }

    fn_fix_apt_sources_if_needed || echo "[警告] 包管理器源检查失败。"

    fn_setup_aggressive_network && echo "[完成] 网络优化加速已创建。" || echo "[警告] 网络优化加速创建失败。"
    echo ""

    fn_setup_journald_volatile; case $? in 0) echo "[完成] Journald 已配置为内存模式。";; 2) echo "[跳过] Journald 已优化。";; esac; echo ""

    # 应用网络配置 + 内联接口优化
    sysctl --system > /dev/null 2>&1 || fn_log "警告" "sysctl --system 出现警告"
    local default_iface=$(ip route | grep default | awk '{print $5}' | head -n1)
    if [[ -n "$default_iface" ]]; then
        ip link set dev "$default_iface" txqueuelen 10000 2>/dev/null || true
        command -v ethtool >/dev/null 2>&1 && ethtool -K "$default_iface" gro off >/dev/null 2>&1 || true
    fi
    echo "[完成] 网络配置已应用，接口已优化。"
    echo ""

    fn_set_system_limits; case $? in 0) echo "[完成] 系统资源限制已更新。";; 2) echo "[跳过] 限制已配置。";; esac; echo ""

    fn_setup_zram_adaptive; case $? in 0) echo "[完成] ZRAM 配置成功。";; 2) echo "[跳过] ZRAM 已激活。";; *) echo "[警告] ZRAM 失败，已启用 swapfile 回退。";; esac; echo ""

    fn_setup_earlyoom; case $? in 0) echo "[完成] earlyoom 已激活。";; 2) echo "[跳过] earlyoom 已激活。";; *) echo "[警告] earlyoom 配置失败。";; esac; echo ""

    fn_prioritize_network_services_auto; case $? in 0) echo "[完成] 网络代理服务优化完成。";; 2) echo "[跳过] 无需优化。";; esac; echo ""

    fn_trim_services_auto; case $? in 0) echo "[完成] 系统服务精简完成。";; 2) echo "[跳过] 无需屏蔽的服务。";; esac; echo ""

    echo "======================================================="
    echo "  系统优化完成！"
    echo "  请重启系统以完全生效所有优化。"
    echo "======================================================="
    fn_log "成功" "系统优化完成。请重启系统以完全生效。"
    fn_show_status_report "noclear"
}


fn_restore_all() {
    echo "[任务] 开始执行撤销优化..."
    fn_log "警告" "开始执行撤销优化... 将从 $ACTION_LOG 恢复。"

    local log_restored=false
    if [ -f "$ACTION_LOG" ] && [ $(grep -vc '^#' "$ACTION_LOG") -gt 0 ]; then
        echo "[成功] 检测到操作日志: $ACTION_LOG (共 $(grep -vc '^#' "$ACTION_LOG") 条操作)。将执行日志反向撤销..."
        fn_log "信息" "检测到有效操作日志，将执行反向撤销。"
        log_restored=true
    else
        echo "[失败] 未找到操作日志或日志为空: $ACTION_LOG。将仅使用备份文件和强制清理。"
        fn_log "错误" "未找到 $ACTION_LOG 或其为空，无法执行日志反向撤销。"
    fi

    echo "[任务]   正在停用 ZRAM 和 Swap..."
    (systemctl disable --now zramswap.service) >> "$LOG_FILE" 2>&1 || true
    swapoff -a >/dev/null 2>&1 || true
    modprobe -r zram >/dev/null 2>&1 || true
    
    if [ "$log_restored" = "true" ]; then
        tac "$ACTION_LOG" | while read -r line; do
            [ -z "$line" ] && continue
            [[ "$line" == \#* ]] && continue
            
            local action=$(echo "$line" | cut -d: -f1)
            local value=$(echo "$line" | cut -d: -f2-)

            case "$action" in
                MASK_SERVICE)
                    echo "[日志撤销] Unmasking $value"
                    fn_log "信息" "[日志撤销] Unmasking $value"
                    (systemctl unmask "$value") >> "$LOG_FILE" 2>&1 || true
                    ;;
                CREATE_FILE)
                    echo "[日志撤销] Removing file/dir $value"
                    fn_log "信息" "[日志撤销] Removing file/dir $value"
                    rm -rf "$value"
                    if [[ "$value" == *.service.d/*.conf ]]; then
                        rmdir "$(dirname "$value")" 2>/dev/null || true
                    fi
                    ;;
                INSTALL_PKG)
                    echo "[日志撤销] Purging package $value"
                    fn_log "信息" "[日志撤销] Purging package $value"
                    if [ ${#PKG_CMD_REMOVE[@]} -gt 0 ]; then
                        fn_wait_for_pkg_lock || fn_log "警告" "包管理器锁等待失败，跳过卸载 $value"
                        ("${PKG_CMD_REMOVE[@]}" "$value") >> "$LOG_FILE" 2>&1
                    fi
                    ;;
                UNINSTALL_PKG) 
                    echo "[日志撤销] Re-installing package $value"
                    fn_log "信息" "[日志撤销] Re-installing package $value"
                    if [ ${#PKG_CMD_INSTALL[@]} -gt 0 ]; then
                        fn_wait_for_pkg_lock || fn_log "警告" "包管理器锁等待失败，跳过安装 $value"
                        ("${PKG_CMD_INSTALL[@]}" "$value") >> "$LOG_FILE" 2>&1
                    fi
                    ;;
                MODIFY_FILE)
                    if [ -f "${value}.bak" ]; then
                        echo "[日志撤销] Restoring $value from ${value}.bak"
                        fn_log "信息" "[日志撤销] Restoring $value from ${value}.bak"
                        mv "${value}.bak" "$value" >> "$LOG_FILE" 2>&1
                    else
                        echo "[日志跳过] 未找到 ${value}.bak，无法恢复 $value"
                        fn_log "警告" "未找到 ${value}.bak，无法恢复 $value"
                    fi
                    ;;
                *)
                    fn_log "警告" "未知的撤销操作: $action"
                    ;;
            esac
        done
        
    fi

    echo "[任务]   正在恢复核心备份文件..."
    
    echo "[任务]     恢复 sysctl..."
    [ -f "${BACKUP_DIR}/sysctl.conf.bak" ] && cp -an "${BACKUP_DIR}/sysctl.conf.bak" /etc/sysctl.conf 2>/dev/null && fn_log "信息" "恢复 /etc/sysctl.conf" || true
    [ -d "${BACKUP_DIR}/sysctl.d.bak" ] && cp -ar "${BACKUP_DIR}/sysctl.d.bak" /etc/sysctl.d/ 2>/dev/null && fn_log "信息" "恢复 /etc/sysctl.d/" || true
    
    cat > /etc/sysctl.d/98-bbr-retention.conf <<'EOF'
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
EOF
    sysctl --system >/dev/null 2>/dev/null || true

    echo "[任务]     恢复 journald..."
    [ -d "${BACKUP_DIR}/journald.conf.d.bak" ] && rm -rf /etc/systemd/journald.conf.d/ && cp -ar "${BACKUP_DIR}/journald.conf.d.bak" /etc/systemd/journald.conf.d/ 2>/dev/null && fn_log "信息" "恢复 journald.conf.d" || true
    systemctl restart systemd-journald >/dev/null 2>/dev/null || true
    
    echo "[任务]     恢复 fstab..."
    [ -f "${BACKUP_DIR}/fstab.bak" ] && cp -an "${BACKUP_DIR}/fstab.bak" /etc/fstab 2>/dev/null && fn_log "信息" "恢复 /etc/fstab" || true

    echo "[任务]     恢复 systemd.conf..."
    [ -f "${BACKUP_DIR}/system.conf.bak" ] && cp -an "${BACKUP_DIR}/system.conf.bak" /etc/systemd/system.conf 2>/dev/null && { systemctl daemon-reexec >/dev/null 2>&1 || true; fn_log "信息" "恢复 /etc/systemd/system.conf"; } || true

    echo "[任务]   正在执行强制配置清理 (确保无残留 vps_optimizert 配置)..."
    
    local files_to_clean=(
        "/etc/sysctl.d/99-vps_optimizert.conf"
        "/etc/apt/apt.conf.d/99-force-ipv4"
        "/etc/systemd/journald.conf.d/10-volatile.conf"
        "/etc/default/zramswap"
        "/swapfile_zram"
        "/etc/default/earlyoom"
        "/etc/sysctl.d/99-vps-extra.conf"
        "/etc/ax-optz.conf"
    )
    
    for f in "${files_to_clean[@]}"; do
        if [ -f "$f" ]; then
            echo "[清理] 移除文件 $f"
            rm -f "$f"
            fn_log "信息" "[清理] 移除 $f"
        fi
    done

    echo "[任务]   正在清理网络服务 drop-in 配置..."
    find /etc/systemd/system/ -type d -name "*.service.d" 2>/dev/null | while read -r dropin_dir; do
        if [ -f "${dropin_dir}/90-vps_optimizert.conf" ]; then
            echo "[清理] 移除配置目录 $dropin_dir"
            rm -rf "$dropin_dir"
            fn_log "信息" "[清理] 移除网络服务配置目录 $dropin_dir"
        fi
    done
    
    echo "[任务]   正在恢复之前启用的服务 (来自 enabled_services.before.txt)..."
    if [ -f "${BACKUP_DIR}/enabled_services.before.txt" ]; then
        while read -r s; do 
            [ -z "$s" ] && continue
            (systemctl enable "$s") >> "$LOG_FILE" 2>&1 || true; 
        done < "${BACKUP_DIR}/enabled_services.before.txt"
    else
        echo "[跳过] 未找到 enabled_services.before.txt，跳过服务启用恢复。"
        fn_log "警告" "未找到 enabled_services.before.txt，跳过服务启用恢复。"
    fi

    (systemctl daemon-reload) >> "$LOG_FILE" 2>&1
    rm -f "$ACTION_LOG"
    
    echo "[完成] 撤销优化完成。"
    fn_log "成功" "撤销优化完成。"
}

fn_show_status_report() {
    if [ "${1:-}" != "noclear" ]; then
        clear
    fi
    
    echo "-------------------- 系统优化状态 ---------------------"
    [ -f /etc/os-release ] && source /etc/os-release
    printf "系统: %s\n" "${PRETTY_NAME:-unknown}"
    printf "内存: %s MB (分层: %s)\n" "$MEM_MB" "${MEMORY_TIER:-未检测}"
    printf "内核: %s\n" "$(uname -r)"
    echo "------------------------------------------------------"

    fn_print_line() {
        local name="$1" status="$2" success_msg="$3" fail_msg="$4" details="${5:-}"
        local status_msg="$fail_msg" details_str="" byte_len char_len visual_width name_pad
        [ "$status" == "true" ] && status_msg="$success_msg"
        [ -n "$details" ] && details_str="$details"
        byte_len=$(echo -n "$name" | LC_ALL=C wc -c)
        char_len=${#name}
        visual_width=$(( char_len + (byte_len - char_len) / 2 ))
        name_pad=$(( ${#name} + 27 - visual_width ))
        printf "  %-${name_pad}s %-18s %s\n" "$name" "$status_msg" "$details_str"
    }

    local sysctl_conf_file="/etc/sysctl.d/99-net.conf"
    local sysctl_status="false"
    local bbr_status="false"
    [ -f "$sysctl_conf_file" ] && sysctl_status="true"
    
    if [ "$(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null)" == "bbr" ] && \
       [ "$(sysctl -n net.core.default_qdisc 2>/dev/null)" == "fq" ]; then
        bbr_status="true"
    fi
    
    fn_print_line "BBR+FQ 加速" "$bbr_status" "[ 已启用 ]" "[ 未启用 ]" ""
    fn_print_line "网络优化加速" "$sysctl_status" "[ 已配置 ]" "[ 未配置 ]" ""
    
    local ipv6_status="false"
    local ipv6_details=""
    if [ "$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null)" == "1" ]; then
        ipv6_status="true"
        ipv6_details="(已禁用)"
    else
        ipv6_status="false"
        ipv6_details="(已启用)"
    fi
    fn_print_line "IPv6 禁用" "$ipv6_status" "[ 已禁用 ]" "[ 已启用 ]" "$ipv6_details"

    local journal_storage
    journal_storage=$(systemd-analyze cat-config systemd/journald.conf | grep -i '^Storage=' | tail -n 1 | cut -d= -f2 2>/dev/null || echo "disk")
    local journal_status="false"
    local journal_details="(模式: ${journal_storage:-disk})"
    if [ "$journal_storage" == "volatile" ]; then
        journal_status="true"
        journal_details="(模式: 仅内存)"
    fi
    fn_print_line "Journald 日志" "$journal_status" "[ 已优化 ]" "[ 未优化 ]" "$journal_details"

    local zram_status="false"
    local zram_details="(未激活)"
    if systemctl is-active zramswap.service > /dev/null 2>&1 && swapon -s | grep -q 'zram'; then
        zram_status="true"
        zram_details="(已激活 ZRAM)"
    elif swapon -s | grep -q 'swapfile_zram'; then
        zram_status="true"
        zram_details="(已激活 Swapfile)"
    fi
    fn_print_line "ZRAM/Swap" "$zram_status" "[ 已优化 ]" "[ 未激活 ]" "$zram_details"

    echo "------------------------------------------------------"
}

fn_toggle_ipv6() {
    local conf="/etc/sysctl.d/99-net.conf"
    local current
    current=$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null)
    if [ "$current" == "1" ]; then
        echo "正在启用 IPv6..."
        sysctl -w net.ipv6.conf.all.disable_ipv6=0 net.ipv6.conf.default.disable_ipv6=0 >/dev/null
        if [ -f "$conf" ]; then
            sed -i '/net.ipv6.conf.*disable_ipv6/d' "$conf" 2>/dev/null || \
            sed -i '' '/net.ipv6.conf.*disable_ipv6/d' "$conf" 2>/dev/null
        fi
        echo "[完成] IPv6 已启用"
        fn_log "信息" "IPv6 已手动启用"
    else
        echo "正在禁用 IPv6..."
        sysctl -w net.ipv6.conf.all.disable_ipv6=1 net.ipv6.conf.default.disable_ipv6=1 >/dev/null
        sysctl -w net.ipv6.conf.lo.disable_ipv6=0 >/dev/null
        if [ -f "$conf" ]; then
            grep -q 'net.ipv6.conf.all.disable_ipv6' "$conf" || \
                printf "\n# IPv6 禁用\nnet.ipv6.conf.all.disable_ipv6 = 1\nnet.ipv6.conf.default.disable_ipv6 = 1\nnet.ipv6.conf.lo.disable_ipv6 = 0\n" >> "$conf"
        fi
        echo "[完成] IPv6 已禁用"
        fn_log "信息" "IPv6 已手动禁用"
    fi
    sysctl --system > /dev/null 2>&1
}

fn_show_menu() {
    while true; do
    clear
    
    # 在菜单上方显示系统优化状态
    fn_show_status_report "noclear"
    echo ""

    echo "==============================================="
    echo " VPS 优化脚本 (ax-optz)"
    echo " 版本: $SCRIPT_VERSION"
    echo " 备份目录: $BACKUP_DIR"
    echo " 日志文件: $LOG_FILE"
    echo "==============================================="
    if fn_check_if_optimized; then
        echo " 1) 重新系统优化"
    else
        echo " 1) 执行系统优化"
    fi
    echo " 2) 撤销优化"
    local ipv6_now
    ipv6_now=$(sysctl -n net.ipv6.conf.all.disable_ipv6 2>/dev/null)
    if [ "$ipv6_now" == "1" ]; then
        echo " 3) IPv6 启用"
    else
        echo " 3) IPv6 禁用"
    fi
    echo " 0) 退出"
    echo "==============================================="

    read -rp "请选择: " CH || true
    case "$CH" in
        1) 
            fn_optimize_auto || true 
            read -rp "按回车返回主菜单..." dummy || true
            ;;
        2) 
            fn_restore_all || true 
            read -rp "按回车返回主菜单..." dummy || true
            ;;
        3)
            fn_toggle_ipv6
            read -rp "按回车返回菜单..." dummy || true
            ;;
        0) 
            break
            ;;
        *) 
            echo "错误: 无效选项。"
            fn_log "错误" "无效选项。"; sleep 1;
            ;;
    esac
    done
}

fn_check_root
fn_detect_os
fn_detect_memory_tier

fn_show_menu
